'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useProjectContext} from './project-context';
import {quantityBrowse,quantityResponse} from '@/lib/quantities/client';
import type {Entry} from '@/lib/autodesk/data';
import type {ProjectConfiguration} from '@/lib/projects/configuration';

export function DocumentConfiguration(){
 const p=useProjectContext(),[sources,setSources]=useState(p.configuration?.documents??[]),[folders,setFolders]=useState<Entry[]>([]),[entries,setEntries]=useState<Entry[]>([]),[next,setNext]=useState<number|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [page,setPage]=useState(0),folderId=folders.at(-1)?.id??null;
 useEffect(()=>{const abort=new AbortController();queueMicrotask(()=>{if(!abort.signal.aborted){setBusy(true);setError('');}});quantityBrowse({operation:folderId?'contents':'roots',hubId:p.hubId,projectId:p.projectId,folderId,page},abort.signal).then(r=>{if(!abort.signal.aborted){setEntries(old=>page?[...old,...r.entries]:r.entries);setNext(r.evidence.nextPage);}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});return()=>abort.abort();},[p.hubId,p.projectId,folderId,page]);
 function choose(e:Entry){if(!['folders','items'].includes(e.type))return;const scope=e.type==='folders'?{kind:'folder' as const,hubId:p.hubId,projectId:p.projectId,folderIds:[...folders.map(f=>f.id),e.id]}:{kind:'file' as const,hubId:p.hubId,projectId:p.projectId,folderIds:folders.map(f=>f.id),itemId:e.id};if(!sources.some(s=>JSON.stringify(s.scope)===JSON.stringify(scope)))setSources(old=>[...old,{scope,label:[...folders.map(f=>f.name),e.name].join(' / ')}]);}
 async function save(){setBusy(true);setError('');try{const r=await quantityResponse<{configuration:ProjectConfiguration}>('/api/projects/configuration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:p.project,moduleId:'documents',command:{action:'save',configuration:{revision:p.configuration?.revision??0,projectName:p.appProject?.name??p.projects.find(x=>x.id===p.projectId)?.name,disciplines:[],documents:sources}}})});p.adoptConfiguration(r.configuration);setNotice('Referencias guardadas en Control Documental.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="configuration-card"><h2>Fuentes de Control Documental</h2><p>Carpetas y archivos de este proyecto. No se requiere modelo ni vista 3D.</p><nav aria-label="Carpeta actual"><button disabled={busy} onClick={()=>{setFolders([]);setPage(0);}}>Proyecto</button>{folders.map((f,i)=><button disabled={busy} key={f.id} onClick={()=>{setFolders(folders.slice(0,i+1));setPage(0);}}>{f.name}</button>)}</nav><div className="configuration-legacy">{entries.map(e=><div key={e.id}><span>{e.name}</span>{e.type==='folders'&&<button disabled={busy} onClick={()=>{setFolders([...folders,e]);setPage(0);}}>Abrir carpeta</button>}<button disabled={busy} onClick={()=>choose(e)}>Incluir</button></div>)}</div>{next!==null&&<button disabled={busy} onClick={()=>setPage(next)}>Más archivos</button>}{busy&&<p role="status">Consultando…</p>}<h3>Fuentes incluidas</h3>{sources.length?<ul>{sources.map((s,i)=><li key={JSON.stringify(s.scope)}>{s.label} <button disabled={busy} onClick={()=>setSources(old=>old.filter((_,n)=>n!==i))}>Quitar</button></li>)}</ul>:<p>Sin fuentes configuradas.</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button className="quantity-primary" disabled={busy} onClick={()=>void save()}>Guardar configuración</button></section>;
}
export function DocumentWorkspace(){const p=useProjectContext();return <div className="project-home"><h1>Control Documental</h1><p>{p.appProject?.name??'Proyecto activo'}</p><Link className="project-secondary" href="/configuracion/documents">Configurar carpetas y archivos</Link>{p.configurationLoading?<p>Cargando fuentes…</p>:p.configurationError?<p role="alert">{p.configurationError}</p>:<section className="configuration-card"><h2>Fuentes del proyecto</h2>{p.configuration?.documents.length?<ul>{p.configuration.documents.map(s=><li key={JSON.stringify(s.scope)}>{s.label}</li>)}</ul>:<p>No configurado. Selecciona las carpetas o archivos que utilizará este módulo.</p>}<p>Referencias de Autodesk; no se copian archivos al seleccionar el proyecto. No hay ejecuciones de Control Documental disponibles todavía.</p></section>}</div>;}
