'use client';
import Link from 'next/link';
import {useState} from 'react';
import {Plus,Settings2,Save,ShieldCheck,ArrowRight} from 'lucide-react';
import {useProjectContext} from './project-context';
import {QuantitySourcePicker} from './quantity-source-picker';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {quantityResponse} from '@/lib/quantities/client';
import {disciplineCatalog,type ProjectConfiguration,type ProjectDiscipline} from '@/lib/projects/configuration';
import type {ModelVersion,QuantitySource,QuantityWorkspace} from '@/lib/quantities/contracts';
import type {AuditWorkspace} from '@/lib/audit/contracts';
import type {Workspace as RegulatoryWorkspace} from '@/lib/coordination/contracts';

export function ProjectConfigurationPage(){const p=useProjectContext();return <div className="project-configuration"><header><p className="eyebrow">CONFIGURACIÓN DEL PROYECTO</p><h1>{p.projects.find(x=>x.id===p.projectId)?.name??'Proyecto activo'}</h1><p>Define una vez la especialidad, el archivo y la vista que usarás al auditar, cubicar y consultar.</p></header>{p.configurationLoading?<p role="status">Cargando configuración…</p>:p.configurationError?<p role="alert">No se pudo cargar la configuración. {p.configurationError} <button onClick={p.reloadConfiguration}>Reintentar</button></p>:<ConfigurationEditor key={`${p.hubId}:${p.projectId}:${p.configuration?.revision??0}`}/>}</div>;}
function ConfigurationEditor(){
 const p=useProjectContext(),[rows,setRows]=useState<ProjectDiscipline[]>(p.configuration?.disciplines??[]),[editing,setEditing]=useState<string|null>(null),[add,setAdd]=useState(false),[code,setCode]=useState('structure'),[customName,setCustomName]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[checks,setChecks]=useState<Record<string,{source:QuantitySource;latest:ModelVersion;validatedAt:string}>>({});
 const [legacy,setLegacy]=useState<{code:string;name:string;source:QuantitySource}[]|null>(null);
 const row=rows.find(d=>d.id===editing),changed=JSON.stringify(rows)!==JSON.stringify(p.configuration?.disciplines??[]);
 const update=(id:string,patch:Partial<ProjectDiscipline>)=>setRows(old=>old.map(d=>d.id===id?{...d,...patch}:d));
 const request=<T,>(command:unknown)=>quantityResponse<T>('/api/projects/configuration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:p.project,command})});
 async function save(){setBusy(true);setError('');try{const r=await request<{configuration:ProjectConfiguration}>({action:'save',configuration:{revision:p.configuration?.revision??0,projectName:p.projects.find(x=>x.id===p.projectId)?.name??p.configuration?.projectName??'Proyecto activo',disciplines:rows}});p.adoptConfiguration(r.configuration);if(!p.selectedDiscipline){const first=r.configuration.disciplines.find(d=>d.enabled);if(first)p.selectDiscipline(first.id);}setNotice('Configuración guardada y verificada en Autodesk.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function validate(){setBusy(true);setError('');setNotice('');const failures:string[]=[];for(const d of rows.filter(d=>d.source)){try{const result=await request<{source:QuantitySource;latest:ModelVersion;validatedAt:string}>({action:'validate',source:d.source});setChecks(old=>({...old,[d.id]:result}));}catch(e){failures.push(`${d.name}: ${(e as Error).message}`);}}setError(failures.join(' · '));setNotice(failures.length?'Validación parcial. Revisa los errores.':'Verificación terminada. Las versiones seleccionadas se conservan hasta que guardes un cambio.');setBusy(false);}
 async function loadLegacy(){setBusy(true);setError('');const query=`?scope=${encodeURIComponent(JSON.stringify(p.project))}`;const result=await Promise.allSettled([quantityResponse<QuantityWorkspace>('/api/quantities'+query),quantityResponse<AuditWorkspace>('/api/audit'+query),quantityResponse<RegulatoryWorkspace>('/api/coordination'+query)]);const found:{code:string;name:string;source:QuantitySource}[]=[];const [q,a,c]=result;
  if(q.status==='fulfilled')for(const d of q.value.configurations)if(d.source)found.push({code:d.specialtyCode,name:disciplineCatalog.find(x=>x.code===d.specialtyCode)?.name??d.specialtyCode,source:d.source});
  if(a.status==='fulfilled'&&a.value.configuration?.source){const d=a.value.configuration;const code=d.discipline==='ESTRUCTURA'?'structure':d.discipline==='ARQUITECTURA'?'architecture':'mep';found.push({code,name:`Auditoría · ${d.discipline}`,source:d.source!});}
  if(c.status==='fulfilled')for(const d of c.value.configurations){const code=({'SAN-01':'sewer','SAN-02':'external-sewer','SAN-03':'cold-water','SAN-04':'external-water','SAN-05':'hot-water'} as Record<string,string>)[d.configuration.systemId];if(code&&d.configuration.source)found.push({code,name:`Normativa · ${disciplineCatalog.find(x=>x.code===code)?.name}`,source:d.configuration.source});}
  setLegacy(found);if(result.some(r=>r.status==='rejected'))setError('Algunas configuraciones anteriores no respondieron. Puedes reintentar sin modificar las existentes.');setBusy(false);
 }
 return <><section className="configuration-card"><div className="configuration-toolbar"><h2>Especialidades y fuentes</h2><button className="quantity-secondary" onClick={()=>setAdd(true)} disabled={busy}><Plus size={15}/>Agregar especialidad</button></div>
 <div className="configuration-table"><table><thead><tr><th>Activa</th><th>Especialidad</th><th>Archivo / versión</th><th>Vista</th><th>Estado</th><th/></tr></thead><tbody>{rows.map(d=>{const v=checks[d.id],isSame=v?.source.version.id===d.source?.version.id,isNew=isSame&&v.latest.id!==d.source?.version.id;return <tr key={d.id}><td><input aria-label={`Activar ${d.name}`} type="checkbox" disabled={busy} checked={d.enabled} onChange={e=>update(d.id,{enabled:e.target.checked})}/></td><td><button className="quantity-text-button" onClick={()=>{p.selectDiscipline(d.id);setEditing(d.id);}}>{d.name}</button>{p.selectedDiscipline?.id===d.id&&<small>Especialidad activa</small>}</td><td>{d.source?<>{d.source.fileName}<small>V{d.source.version.number} · {d.source.version.createdAt?new Date(d.source.version.createdAt).toLocaleDateString('es-CL'):'Fecha no disponible'}</small></>:'Sin archivo'}</td><td>{d.source?.view?.name??'Sin vista'}</td><td><span className={`configuration-state ${isNew?'outdated':isSame?'current':''}`}>{isNew?'Nueva versión disponible':isSame?'Versión actual verificada':d.source?.view?'Configurada · por verificar':'Pendiente'}</span>{isNew&&<div className="configuration-version-actions"><button onClick={()=>{update(d.id,{source:{...d.source!,version:v.latest,view:null},lastValidatedAt:null});setEditing(d.id);}}>Actualizar a V{v.latest.number}</button><button onClick={()=>setNotice(`Se mantiene V${d.source!.version.number} de ${d.name}. La última publicación es V${v.latest.number}.`)}>Mantener versión</button><details><summary>Comparar versiones</summary><p>Configurada: V{d.source!.version.number} · {d.source!.version.createdAt??'Fecha no disponible'}<br/>Última: V{v.latest.number} · {v.latest.createdAt??'Fecha no disponible'}</p><p>Comparación de publicaciones. Las diferencias de elementos o cantidades requieren ejecuciones de ambas versiones.</p></details></div>}</td><td><button className="quantity-secondary" disabled={busy} onClick={()=>setEditing(d.id)}><Settings2 size={14}/>Editar</button></td></tr>;})}</tbody></table></div>{!rows.length&&<div className="configuration-empty"><h3>Configura la primera especialidad</h3><p>Elige un archivo desde cualquier carpeta de Autodesk o recupera una selección que ya usabas en otro módulo.</p><button className="quantity-secondary" disabled={busy} onClick={()=>void loadLegacy()}>Recuperar configuraciones existentes</button></div>}
 {rows.length>0&&<details><summary>Configuraciones anteriores de los módulos</summary><p>Adoptar una fuente no elimina resultados ni sustituye reglas técnicas.</p><button className="quantity-text-button" disabled={busy} onClick={()=>void loadLegacy()}>Consultar fuentes anteriores</button></details>}
 {legacy&&<div className="configuration-legacy">{legacy.length?legacy.map((d,i)=><div key={i}><span><strong>{d.name}</strong><small>{d.source.fileName} · V{d.source.version.number} · {d.source.view?.name??'Sin vista'}</small></span><button disabled={busy||rows.some(r=>r.code===d.code)} onClick={()=>{const id=crypto.randomUUID();setRows(old=>[...old,{id,code:d.code,name:disciplineCatalog.find(x=>x.code===d.code)?.name??d.name,enabled:true,source:d.source,lastValidatedAt:null}]);}}>Usar esta fuente</button></div>):<p>No se encontraron fuentes guardadas.</p>}</div>}
 </section>{error&&<p role="alert" className="quantity-error">{error}</p>}{notice&&<p role="status" className="project-notice">{notice}</p>}<div className="configuration-toolbar"><button className="quantity-primary" disabled={busy||!changed||rows.some(d=>d.enabled&&!d.source?.view)} onClick={()=>void save()}><Save size={16}/>{busy?'Procesando…':'Guardar configuración'}</button><button className="quantity-secondary" disabled={busy||!rows.some(d=>d.source)} onClick={()=>void validate()}><ShieldCheck size={16}/>Validar configuración</button><small>{p.configuration?`Revisión ${p.configuration.revision} · Guardada ${new Date(p.configuration.updatedAt).toLocaleString('es-CL')}`:'Sin configuración guardada'}</small></div>
 {p.configuration&&<div className="configuration-next"><Link href="/auditoria-bim">Auditar <ArrowRight size={15}/></Link><Link href="/cubicaciones">Cubicar <ArrowRight size={15}/></Link><Link href="/consultar-ia">Consultar IA <ArrowRight size={15}/></Link></div>}
 <Dialog open={!!row} onOpenChange={open=>{if(!open)setEditing(null);}}><DialogContent className="quantity-page quantity-modal"><DialogTitle>{row?.name} · Archivo y vista</DialogTitle><DialogDescription>La selección será compartida por las herramientas del proyecto. Selecciona una vista 3D y guarda la configuración.</DialogDescription>{row&&<QuantitySourcePicker key={row.id} project={p.project} source={row.source} disabled={busy} onChange={source=>update(row.id,{source,lastValidatedAt:null})}/>}<button className="quantity-primary" onClick={()=>setEditing(null)}>Listo</button></DialogContent></Dialog>
 <Dialog open={add} onOpenChange={setAdd}><DialogContent><DialogTitle>Agregar especialidad</DialogTitle><DialogDescription>Activa sólo las especialidades que utilizarás en este proyecto.</DialogDescription><label>Especialidad<select value={code} onChange={e=>setCode(e.target.value)}>{disciplineCatalog.filter(d=>!rows.some(r=>r.code===d.code)).map(d=><option key={d.code} value={d.code}>{d.name}</option>)}<option value="custom">Otra especialidad</option></select></label>{code==='custom'&&<label>Nombre<input value={customName} onChange={e=>setCustomName(e.target.value)} maxLength={150}/></label>}<button className="quantity-primary" disabled={code==='custom'?!customName.trim():rows.some(r=>r.code===code)} onClick={()=>{const id=crypto.randomUUID();setRows(old=>[...old,{id,code:code==='custom'?`custom-${id}`:code,name:code==='custom'?customName.trim():disciplineCatalog.find(d=>d.code===code)!.name,enabled:true,source:null,lastValidatedAt:null}]);setAdd(false);setEditing(id);}}>Agregar</button></DialogContent></Dialog></>;
}
