"use client";
import { useMemo, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { settingsSchema, type CalculationSettings, type ModelBinding, type SlabCandidate, type ViewCalculation } from '@/lib/quantities-v2/contracts';
import { slabCandidates } from '@/public/quantity-v2/levels.js';
import { AZA_SOURCE, addAzaWeights } from '@/public/quantity-v2/rebar-reference.js';
import { numberText } from '@/lib/quantities-v2/presentation';
export function QuantityCriteria({settings,data,binding,busy,onApply}:{settings:CalculationSettings;data:ViewCalculation|null;binding:ModelBinding|null;busy:boolean;onApply:(settings:CalculationSettings)=>Promise<void>}){
 const [draft,setDraft]=useState(settings),[error,setError]=useState('');
 const candidates=useMemo(()=>data?slabCandidates(data.records,draft.levelToleranceM) as SlabCandidate[]:[],[data,draft.levelToleranceM]);
 const slabs=useMemo(()=>{const groups=new Map<string,{name:string;ids:number[]}>();for(const r of data?.records??[]){if(r.category!=='Floors'||r.specialty!=='Hormigón')continue;const key=r.text.type.value??r.text.family.value??r.name;const group=groups.get(key)??{name:key,ids:[]};group.ids.push(r.dbId);groups.set(key,group);}return [...groups.values()];},[data]);
 function tolerance(mm:number){setDraft(d=>({...d,levelToleranceM:mm/1000,levelReferences:[]}));}
 function reference(c:SlabCandidate,index:number,selected:boolean){setDraft(d=>({...d,levelBinding:binding?{urn:binding.urn,viewId:binding.viewId}:null,levelReferences:selected?[...d.levelReferences,{id:c.id,dbIds:c.dbIds,label:index===0?'Fundación':`Piso ${index}`,aliases:[]}]:d.levelReferences.filter(r=>r.id!==c.id)}));}
 async function submit(){const parsed=settingsSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues[0].message);return;}if(draft.levelReferences.length===1){setError('Confirma al menos dos referencias para construir un intervalo, o desmarca todas.');return;}setError('');try{await onApply(parsed.data);}catch(e){setError((e as Error).message);}}
 return <div className="qv2-criteria">
 <section><h3>Pisos por losas de referencia</h3><p className="quantity-help">Tolerancias pequeñas para agrupar cotas superiores. 2 mm es una propuesta inicial del proyecto; no una tolerancia normativa. Cambiarla requiere revisar los grupos nuevamente.</p><div className="quantity-inline-actions">{[1,2,5].map(mm=><button key={mm} className="quantity-secondary" aria-pressed={draft.levelToleranceM===mm/1000} disabled={busy} onClick={()=>tolerance(mm)}>{mm} mm</button>)}<label>Tolerancia personalizada [mm]<input aria-label="Tolerancia personalizada en milímetros" type="number" min="0.1" max="50" step="0.1" value={Number.isFinite(draft.levelToleranceM)?draft.levelToleranceM*1000:''} onChange={e=>tolerance(e.target.valueAsNumber)} disabled={busy}/></label></div>
 <p className="quantity-help">Confirma solo las plataformas principales: revisa área, cota y losas incluidas. Los balcones y descansos pequeños no deben generar pisos. El nombre propuesto es editable. Cada intervalo toma el nombre de su losa superior.</p>
 {!candidates.length?<p className="quantity-warning">{data?'No se identificaron losas horizontales de Hormigón con geometría verificable en esta vista.':'Carga y lee la vista para detectar sus losas.'}</p>:<div className="qv2-config-table"><table><thead><tr><th>Usar</th><th>Cota superior / área</th><th>Elementos / nivel Revit</th><th>Nombre del piso</th></tr></thead><tbody>{candidates.map((c,i)=>{const ref=draft.levelReferences.find(r=>r.id===c.id);return <tr key={c.id}><td><input type="checkbox" aria-label={`Usar losas a cota ${numberText(c.z)} metros`} checked={Boolean(ref)} disabled={busy} onChange={e=>reference(c,i,e.target.checked)}/></td><td>{numberText(c.z)} m<br/>{numberText(c.area)} m² <small>({numberText(c.relativeArea*100,1)}% del grupo mayor)</small></td><td>{c.dbIds.length} losas<details><summary>Ver referencias</summary>dbId: {c.dbIds.join(', ')}<br/>{c.originalLevels.join(', ')||'Nivel Revit no disponible'}</details></td><td><input aria-label={`Nombre para losas a cota ${numberText(c.z)}`} disabled={!ref||busy} value={ref?.label??''} placeholder="Nombre confirmado" onChange={e=>setDraft(d=>({...d,levelReferences:d.levelReferences.map(r=>r.id===c.id?{...r,label:e.target.value}:r)}))}/></td></tr>;})}</tbody></table></div>}
 <p className="quantity-help">La asignación usa centroide y extensión vertical. Si un elemento cruza varios pisos, se informa el predominante y no se divide su cantidad. Los casos sin evidencia quedan como «Piso no resuelto».</p></section>
 <section><h3>Moldaje de losas</h3><p className="quantity-help">Criterio confirmado: fondo + cantos por defecto. Los tipos/familias identificados como radier o losa de fundación usan sólo cantos. Puedes configurar una excepción por tipo para esta vista y versión; el criterio de cálculo no se presenta como una condición de apoyo extraída de Revit.</p>{slabs.length?<div className="qv2-config-table"><table><thead><tr><th>Tipo publicado</th><th>Elementos</th><th>Criterio por tipo</th></tr></thead><tbody>{slabs.map(g=>{const roles=[...new Set(g.ids.map(id=>draft.slabRoles.find(r=>r.dbId===id)?.role??''))];return <tr key={g.name}><td>{g.name}</td><td>{g.ids.length}</td><td><select aria-label={`Apoyo de ${g.name}`} disabled={busy} value={roles.length===1?roles[0]:''} onChange={e=>{const role=e.target.value as 'ground'|'elevated'|'';setDraft(d=>({...d,levelBinding:binding?{urn:binding.urn,viewId:binding.viewId}:null,slabRoles:[...d.slabRoles.filter(r=>!g.ids.includes(r.dbId)),...(role?g.ids.map(dbId=>({dbId,role})):[])]}));}}><option value="">{roles.length===1?'Automático · fondo + cantos; radier/fundación sólo cantos':'Mixto · conserva excepciones por elemento'}</option><option value="ground">Terreno o fundación · solo cantos</option><option value="elevated">Elevada · fondo y cantos</option></select></td></tr>;})}</tbody></table></div>:<p className="quantity-help">No hay losas de Hormigón disponibles.</p>}</section>
 <section><h3>Pesos nominales de enfierradura</h3><p className="quantity-help">Peso nominal = largo individual × cantidad de barras × kg/m del diámetro. <a href={AZA_SOURCE} target="_blank" rel="noopener noreferrer">Consultar ficha AZA · página 2, tabla 1.2</a>.</p><button className="quantity-secondary" disabled={busy||!data} onClick={()=>setDraft(d=>({...d,rebarWeightTable:addAzaWeights(d.rebarWeightTable,data?.records??[])}))}>Agregar pesos AZA para diámetros de esta vista</button><p className="quantity-help">Ø8, 10, 12, 16, 18 y 22 mm. Agrega los coeficientes faltantes; conserva los ya configurados. Revisa y guarda para aplicarlos al proyecto.</p><p className="quantity-help">Introduce los coeficientes de tu tabla validada. Sin un kg/m con fuente y versión, se muestran diámetros y largos disponibles y el peso queda pendiente.</p><div className="qv2-config-table"><table><thead><tr><th>Diámetro [mm]</th><th>kg/m</th><th>Fuente</th><th>Versión</th><th/></tr></thead><tbody>{draft.rebarWeightTable.map((r,i)=><tr key={i}><td><input aria-label={`Diámetro ${i+1}`} type="number" min="0" step="any" value={r.diameter||''} disabled={busy} onChange={e=>setDraft(d=>({...d,rebarWeightTable:d.rebarWeightTable.map((v,j)=>j===i?{...v,diameter:e.target.valueAsNumber}:v)}))}/></td><td><input aria-label={`Peso kg por metro ${i+1}`} type="number" min="0" step="any" value={r.unit_weight_kg_m||''} disabled={busy} onChange={e=>setDraft(d=>({...d,rebarWeightTable:d.rebarWeightTable.map((v,j)=>j===i?{...v,unit_weight_kg_m:e.target.valueAsNumber}:v)}))}/></td><td><input aria-label={`Fuente de peso ${i+1}`} value={r.source} disabled={busy} onChange={e=>setDraft(d=>({...d,rebarWeightTable:d.rebarWeightTable.map((v,j)=>j===i?{...v,source:e.target.value}:v)}))}/></td><td><input aria-label={`Versión de tabla ${i+1}`} value={r.version} disabled={busy} onChange={e=>setDraft(d=>({...d,rebarWeightTable:d.rebarWeightTable.map((v,j)=>j===i?{...v,version:e.target.value}:v)}))}/></td><td><button className="quantity-icon-button" aria-label={`Quitar diámetro ${i+1}`} disabled={busy} onClick={()=>setDraft(d=>({...d,rebarWeightTable:d.rebarWeightTable.filter((_,j)=>j!==i)}))}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div><button className="quantity-text-button" disabled={busy} onClick={()=>setDraft(d=>({...d,rebarWeightTable:[...d.rebarWeightTable,{diameter:0,unit_weight_kg_m:0,source:'',version:''}]}))}><Plus size={14}/>Agregar diámetro</button></section>
 {error&&<p className="quantity-error" role="alert">{error}</p>}<button className="quantity-primary" disabled={busy||!binding} onClick={()=>void submit()}>{busy?'Guardando…':'Confirmar y guardar criterios'}</button>
 </div>;
}
