"use client";
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Box, Layers, Weight, SlidersHorizontal, Settings2, RefreshCw, Table2, FileDown, ArrowLeftRight, Undo2 } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from './ui/dialog';
import { QuantitySourcePicker } from './quantity-source-picker';
import { QuantityV2Viewer, type VisualRequest } from './quantity-v2-viewer';
import { QuantityCriteria } from './quantity-v2-criteria';
import { QuantityElementEvidence } from './quantity-v2-evidence';
import { quantityCommand } from '@/lib/quantities/client';
import type { ModelVersion, ModelView, QuantityConfiguration, QuantityProject, QuantitySource } from '@/lib/quantities/contracts';
import { blankFilters, settingsSchema, type CalculationSettings, type ModelBinding, type ModelElement, type ViewCalculation, type ViewFilters } from '@/lib/quantities-v2/contracts';
import { defaultSettings, compareCalculations } from '@/public/quantity-v2/quantity-service.js';
import { coverageText, facets, metricLabels, metricUnits, numberText, presentation, type Metric } from '@/lib/quantities-v2/presentation';
const metrics:Metric[]=['concrete','formwork','rebar'];
const icons={concrete:Box,formwork:Layers,rebar:Weight};
type Versions={versions:ModelVersion[];latest:ModelVersion;nextPage:number|null};
export function QuantityModelDesk({project,projectName,configuration,openConfiguration,onSave}:{project:QuantityProject;projectName:string;configuration:QuantityConfiguration;openConfiguration:boolean;onSave:(value:QuantityConfiguration)=>void}){
 const [source,setSource]=useState<QuantitySource|null>(configuration.source);
 const [settings,setSettings]=useState<CalculationSettings>(()=>settingsSchema.parse(configuration.calculationSettings??defaultSettings()));
 const [sourceOpen,setSourceOpen]=useState(openConfiguration||!configuration.source?.view),[criteriaOpen,setCriteriaOpen]=useState(false),[comparisonOpen,setComparisonOpen]=useState(false);
 const [data,setData]=useState<ViewCalculation|null>(null),[snapshots,setSnapshots]=useState<ViewCalculation[]>([]),[compareId,setCompareId]=useState('');
 const [filters,setFilters]=useState<ViewFilters>(blankFilters),[visualRequest,setVisualRequest]=useState<VisualRequest|null>(null),[recalculate,setRecalculate]=useState(0);
 const [evidence,setEvidence]=useState<ModelElement[]|null>(null),[mobileTab,setMobileTab]=useState('model');
 const [versions,setVersions]=useState<Versions|null>(null),[versionError,setVersionError]=useState(''),[refreshVersions,setRefreshVersions]=useState(0);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const binding=useMemo<ModelBinding|null>(()=>source?.view&&source.version.modelId?{projectId:project.projectId,itemId:source.scope.itemId,versionId:source.version.id,versionNumber:source.version.number,urn:source.version.modelId,viewId:source.view.id,fileName:source.fileName,viewName:source.view.name,projectName}:null,[source,project.projectId,projectName]);
 const key=binding?JSON.stringify([binding.projectId,binding.itemId,binding.versionId,binding.viewId]):'';
 const live=data&&data.binding.urn===binding?.urn&&data.binding.viewId===binding?.viewId?data:null;
 const result=useMemo(()=>live?presentation(live,filters):null,[live,filters]);
 const options=useMemo(()=>live?facets(live,filters):{specialties:[],categories:[],floors:[]},[live,filters]);
 const receive=useCallback((value:ViewCalculation|null)=>{setData(value);if(value)setSnapshots(old=>[value,...old.filter(s=>s.binding.urn!==value.binding.urn||s.binding.viewId!==value.binding.viewId)].slice(0,6));},[]);
 const changed=source?.scope.itemId!==configuration.source?.scope.itemId||source?.version.id!==configuration.source?.version.id||source?.view?.id!==configuration.source?.view?.id||JSON.stringify(settings)!==JSON.stringify(configuration.calculationSettings??defaultSettings());
 useEffect(()=>{if(!source)return;const controller=new AbortController();void quantityCommand<Versions>(project,{action:'versions',file:source.scope},controller.signal).then(v=>{if(!controller.signal.aborted)setVersions(v);}).catch(e=>{if(!controller.signal.aborted)setVersionError(e.message);});return()=>controller.abort();},[project,source,refreshVersions]);
 function changeSource(next:QuantitySource|null){setVersions(null);setVersionError('');const same=next?.version.modelId===source?.version.modelId&&next?.view?.id===source?.view?.id;if(!same){setSettings(s=>({...s,levelBinding:null,levelReferences:[],manualFloors:[],slabRoles:[],foundationFaces:[]}));setData(null);setFilters(blankFilters);setVisualRequest(null);setEvidence(null);}setSource(next);setNotice('');}
 async function save(next=settings){if(!source?.view)throw Error('Selecciona archivo, versión y vista antes de guardar.');setBusy(true);setError('');try{const parsed=settingsSchema.parse(next);const saved=await quantityCommand<QuantityConfiguration>(project,{action:'save',id:configuration.id,revision:configuration.revision,templateVersionId:configuration.templateVersionId,source:{scope:source.scope,versionId:source.version.id,viewId:source.view.id},calculationSettings:parsed});onSave(saved);setData(null);setVisualRequest(null);setSettings(parsed);setNotice('Fuente y criterios guardados en el proyecto.');}finally{setBusy(false);}}
 async function changeVersion(which:'latest'|'previous'){if(!source)return;setBusy(true);setError('');try{let found=await quantityCommand<Versions>(project,{action:'versions',file:source.scope});setVersions(found);let previous=found.versions.filter(v=>v.number<source.version.number).sort((a,b)=>b.number-a.number)[0];let pages=0;while(which==='previous'&&!previous&&found.nextPage!==null&&pages++<20){found=await quantityCommand<Versions>(project,{action:'versions',file:source.scope,page:found.nextPage});previous=found.versions.filter(v=>v.number<source.version.number).sort((a,b)=>b.number-a.number)[0];}const version=which==='latest'?found.latest:previous;if(!version)throw Error(found.nextPage!==null?'No se terminó de consultar el historial. Selecciona la versión en la configuración.':'No hay una versión anterior disponible.');if(version.id===source.version.id){setNotice('La versión activa coincide con la última publicación consultada.');return;}const available=await quantityCommand<{views:ModelView[]}>(project,{action:'views',file:source.scope,versionId:version.id});const view=available.views.find(v=>v.id===source.view?.id)??null;changeSource({...source,version,view});if(!view){setSourceOpen(true);setNotice('La otra versión tiene identificadores de vista diferentes. Selecciona su vista publicada para continuar.');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function filter(field:keyof ViewFilters,value:string){setVisualRequest(null);setFilters(f=>({...f,[field]:value}));}
 function locate(ids:number[]){setVisualRequest(previous=>({id:(previous?.id??0)+1,dbIds:ids,action:'isolate'}));setEvidence(null);setMobileTab('model');}
 async function foundationFaces(dbId:number){if(!binding)return;await save({...settings,levelBinding:{urn:binding.urn,viewId:binding.viewId},foundationFaces:[...settings.foundationFaces.filter(r=>r.dbId!==dbId),{dbId,confirmed:true}]});setEvidence(null);}
 async function manualFloor(dbId:number,label:string){if(!binding)return;await save({...settings,levelBinding:{urn:binding.urn,viewId:binding.viewId},manualFloors:[...settings.manualFloors.filter(r=>r.dbId!==dbId),{dbId,label}]});setEvidence(null);}
 function exportEvidence(){if(!live)return;const blob=new Blob([JSON.stringify({...live,activeFilters:filters,filteredDbIds:result?.records.map(r=>r.dbId)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`cubicacion-V${live.binding.versionNumber}-${new Date().toISOString().slice(0,10)}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const previous=snapshots.find(s=>`${s.binding.urn}:${s.binding.viewId}`===compareId);
 const comparison=previous&&live&&previous.binding.itemId===live.binding.itemId?compareCalculations(previous,live):null;
 const versionState=versionError?'Versión por verificar':!versions?'Consultando versión…':versions.latest.id===source?.version.id?'Actualizada':versions.latest.number>(source?.version.number??0)?'Nueva versión disponible':'Versión por verificar';
 return <div className={`quantity-desk-stage qv2-desk mobile-${mobileTab}`}>
 <div className="quantity-context-topbar qv2-context"><div className="qv2-context-source"><strong title={source?.fileName}>{source?.fileName??'Selecciona un modelo RVT'}</strong><span title={source?.view?.name}>{source?.view?.name??'Vista no seleccionada'} · {source?`V${source.version.number}`:'Sin versión'}</span><small>{versionState}{changed?' · Cambios sin guardar':''}</small></div><div className="quantity-top-actions"><button className="quantity-primary" disabled={!source||busy} onClick={()=>void changeVersion('latest')}><RefreshCw size={14}/>Actualizar versión</button><button className="quantity-secondary" disabled={!source||busy} onClick={()=>void changeVersion('previous')}><Undo2 size={14}/>Versión anterior</button><button className="quantity-secondary" disabled={!live} onClick={()=>setComparisonOpen(true)}><ArrowLeftRight size={14}/>Comparar versiones</button><button className="quantity-secondary" onClick={()=>setSourceOpen(true)}><Settings2 size={14}/>Archivo y vista</button></div></div>
 {(error||versionError)&&<p className="quantity-error" role="alert">{error||versionError}</p>}{notice&&<p className="qv2-notice" role="status">{notice}</p>}
 <div className="qv2-mobile-tabs"><button aria-pressed={mobileTab==='model'} onClick={()=>setMobileTab('model')}>Modelo BIM</button><button aria-pressed={mobileTab==='data'} onClick={()=>setMobileTab('data')}>Cubicación y filtros</button></div>
 <div className="quantity-desk-board"><section className="quantity-model quantity-panel" aria-label="Modelo BIM"><div className="quantity-panel-heading"><Box size={20}/><div><h2>Modelo BIM</h2><p>{projectName}</p></div><button className="quantity-text-button" onClick={()=>setSourceOpen(true)}>Configurar archivo y vista</button></div>{binding&&source?.view?.role==='3d'?<QuantityV2Viewer key={key} project={project} source={source} binding={binding} settings={settings} filters={filters} visualRequest={visualRequest} onResult={receive} recalculate={recalculate}/>:<div className="quantity-viewer-empty"><Box size={40}/><h3>{source?.view?.role==='2d'?'Selecciona una vista 3D':'Modelo BIM no cargado'}</h3><p>Elige un RVT, su versión y una vista publicada para leer sus elementos.</p><button className="quantity-primary" onClick={()=>setSourceOpen(true)}>Configurar fuente BIM</button></div>}<div className="quantity-model-bottom"><span>{versions?`Última publicación consultada: V${versions.latest.number}`:'Publicación por verificar'}</span><button className="quantity-text-button" onClick={()=>{setVersions(null);setVersionError('');setRefreshVersions(n=>n+1);}}>Verificar publicación</button></div></section>
 <div className="quantity-data-column"><section className="quantity-panel quantity-filters"><div className="quantity-panel-heading"><SlidersHorizontal size={17}/><h2>Filtros de cubicación</h2><button className="quantity-text-button" disabled={!live} onClick={()=>{setFilters(blankFilters);setVisualRequest(null);}}>Limpiar</button></div><div className="quantity-filter-fields">{([['specialty','Especialidad',options.specialties],['category','Categoría Revit',options.categories],['floor','Piso / Nivel',options.floors]] as [keyof ViewFilters,string,string[]][]).map(([field,label,values])=><label key={field}>{label}<select value={filters[field]} disabled={!live} onChange={e=>filter(field,e.target.value)}><option value="">Todos</option>{values.map(v=><option key={v}>{v}</option>)}</select></label>)}</div></section>
 <section className="quantity-panel quantity-summary"><div className="quantity-panel-heading"><Layers size={17}/><h2>Resumen ejecutivo</h2><button className="quantity-text-button" disabled={!binding} onClick={()=>{setData(null);setVisualRequest(null);setRecalculate(n=>n+1);}}><RefreshCw size={13}/>Recalcular</button></div><div className="quantity-kpis">{metrics.map((metric,i)=>{const Icon=icons[metric],coverage=result?.coverage[metric];return <button key={metric} className={`quantity-kpi kpi-${i}`} title="Aislar los elementos que forman esta cubicación" disabled={!coverage?.eligible} onClick={()=>locate(result!.records.filter(e=>metric==='rebar'?e.specialty==='Enfierradura':e.specialty==='Hormigón').map(e=>e.dbId))}><Icon/><div><h3>{metricLabels[metric]}</h3><span>{metricUnits[metric]}</span></div><strong className={coverage?.total==null?'quantity-no-value':''}>{coverageText(coverage)}</strong><small className="quantity-variation">{coverage?`${coverage.read} / ${coverage.eligible} con cantidad`:'Esperando lectura'}</small></button>;})}</div><div className="qv2-coverage"><button className="quantity-text-button" onClick={()=>setCriteriaOpen(true)}>Configurar pisos, moldaje y pesos</button>{live&&<button className="quantity-text-button" onClick={()=>setEvidence(live.records)}>Cobertura: {live.coverage.inspected} leídos · {live.coverage.unclassified} fuera de especialidades del alcance</button>}</div></section>
 <section className="quantity-panel quantity-detail"><div className="quantity-panel-heading"><Table2 size={17}/><h2>Partidas de la vista</h2><button className="quantity-text-button" disabled={!live} onClick={exportEvidence}><FileDown size={13}/>Exportar evidencia</button></div><div className="quantity-grid-scroll"><table><thead><tr><th>Categoría / piso</th><th>Elementos</th><th>Hormigón<small>m³</small></th><th>Moldaje<small>m²</small></th><th>Enfierradura<small>Ø mm · largo m · kg/m · kg</small></th></tr></thead><tbody>{result?.rows.map(row=><tr key={row.id}><td><button onClick={()=>locate(row.dbIds)} title="Aislar grupo">{row.category}<br/><small>{row.floor}</small></button></td><td><button onClick={()=>setEvidence(row.elements)}>{row.count} · Ver</button></td><td>{row.specialty==='Hormigón'?coverageText(row.quantities.concrete):'No aplica'}</td><td>{row.specialty==='Hormigón'?coverageText(row.quantities.formwork):'No aplica'}</td><td>{row.specialty==='Enfierradura'?<><strong>Ø {numberText(row.diameterMm)}</strong><br/>L: {numberText(row.totalLengthM)}<br/>kg/m: {numberText(row.unitWeightKgM)}<br/><strong>{coverageText(row.quantities.rebar)} kg</strong></>:'No aplica'}</td></tr>)}</tbody>{result&&result.records.length>0&&<tfoot><tr><th>Total / subtotal disponible</th><td>{result.records.length}</td>{metrics.map(m=><td key={m}>{coverageText(result.coverage[m])}</td>)}</tr></tfoot>}</table>{!result?.rows.length&&<div className="quantity-table-empty"><Table2 size={28}/><strong>{live?'Sin elementos para estos filtros':'Esperando lectura de la vista'}</strong><p>{live?'Se incluyen Hormigón y Enfierradura según parámetros publicados y tus asociaciones confirmadas. Revisa la cobertura para ver las reglas y los datos que faltan.':'Las cantidades se calculan al cargar una vista 3D. Los datos ausentes quedan pendientes.'}</p></div>}</div></section></div></div>
 <div className="quantity-workspace-footer"><span>{live?`${result?.records.length??0} elementos filtrados · ${live.coverage.unresolvedFloors} pisos sin resolver en la vista`:'Fuente pendiente de lectura'} · Las acciones del visor no modifican las sumas.</span><span>Revit + cálculo determinístico</span></div>
 <Dialog open={sourceOpen} onOpenChange={setSourceOpen}><DialogContent className="quantity-page quantity-modal"><DialogTitle>Configurar fuente BIM</DialogTitle><DialogDescription>{projectName}. Elige el archivo, la versión y su vista 3D publicada.</DialogDescription><QuantitySourcePicker key={source?.scope.itemId} project={project} source={source} onChange={changeSource} disabled={busy}/><p className="quantity-help">Plantilla: Hormigón, Moldaje y Enfierradura · reglas de esta mesa de trabajo. Al cambiar de versión o vista se revisan nuevamente las referencias de pisos.</p>{error&&<p role="alert" className="quantity-error">{error}</p>}<div className="quantity-inline-actions"><button className="quantity-primary" disabled={!source?.view||busy} onClick={()=>void save().then(()=>setSourceOpen(false)).catch(e=>setError(e.message))}>{busy?'Guardando…':'Guardar configuración'}</button><button className="quantity-secondary" disabled={!source?.view||busy} onClick={()=>setSourceOpen(false)}>Ver y calcular</button></div></DialogContent></Dialog>
 <Dialog open={criteriaOpen} onOpenChange={setCriteriaOpen}><DialogContent className="quantity-page quantity-modal qv2-wide-modal"><DialogTitle>Criterios de cubicación</DialogTitle><DialogDescription>Revisa y confirma los criterios de {source?.fileName??'el modelo'} · {source?`V${source.version.number}`:'sin versión'}.</DialogDescription>{criteriaOpen&&<QuantityCriteria settings={settings} binding={binding} data={live} busy={busy} onApply={async value=>{await save(value);setCriteriaOpen(false);}}/>}</DialogContent></Dialog>
 <Dialog open={Boolean(evidence)} onOpenChange={open=>{if(!open)setEvidence(null);}}><DialogContent className="quantity-page quantity-modal qv2-wide-modal"><DialogTitle>Elementos y procedencia</DialogTitle><DialogDescription>Datos extraídos y fórmulas aplicadas. Cantidades en unidades métricas.</DialogDescription>{evidence&&<QuantityElementEvidence key={evidence.map(e=>e.dbId).join(',')} records={evidence} busy={busy} onLocate={locate} onFloor={manualFloor} onFoundation={foundationFaces}/>}</DialogContent></Dialog>
 <Dialog open={comparisonOpen} onOpenChange={setComparisonOpen}><DialogContent className="quantity-page quantity-modal qv2-wide-modal"><DialogTitle>Comparación de versiones</DialogTitle><DialogDescription>Compara lecturas realizadas en esta sesión del mismo archivo. Las vistas y criterios se identifican por separado.</DialogDescription><p className="quantity-help">Para agregar otra lectura, utiliza «Versión anterior» o configura otra versión y carga su vista. Conservamos hasta seis lecturas en esta mesa; no se presentan como un historial guardado.</p><label>Lectura anterior<select value={compareId} onChange={e=>setCompareId(e.target.value)}><option value="">Seleccionar lectura</option>{snapshots.filter(s=>s.binding.itemId===binding?.itemId&&s.binding.versionId!==binding?.versionId).map(s=><option key={`${s.binding.urn}:${s.binding.viewId}`} value={`${s.binding.urn}:${s.binding.viewId}`}>V{s.binding.versionNumber} · {s.binding.viewName} · {new Date(s.calculatedAt).toLocaleTimeString('es-CL')}</option>)}</select></label>{comparison&&<><p>Anterior: V{comparison.previous.versionNumber} · {comparison.previous.viewName}<br/>Actual: V{comparison.current.versionNumber} · {comparison.current.viewName}</p>{comparison.rulesChanged&&<p className="quantity-warning">Los criterios cambiaron entre lecturas. La diferencia no puede atribuirse únicamente al modelo.</p>}{comparison.previous.viewId!==comparison.current.viewId&&<p className="quantity-warning">Las vistas tienen identificadores distintos. Comprueba que cubran el mismo alcance.</p>}<div className="qv2-config-table"><table><thead><tr><th>Métrica</th><th>Anterior</th><th>Actual</th><th>Diferencia</th></tr></thead><tbody>{comparison.metrics.map(m=><tr key={m.metric}><td>{metricLabels[m.metric as Metric]}</td><td>{coverageText(m.previous)}</td><td>{coverageText(m.current)}</td><td>{m.difference===null?'No calculable con cobertura parcial':numberText(m.difference)}</td></tr>)}</tbody></table></div><p className="quantity-help">No se infieren altas o bajas de elementos a partir de dbIds entre versiones.</p></>}</DialogContent></Dialog>
 </div>;
}
