'use client';
import {useEffect,useRef,useState} from 'react';
import {quantityResponse} from '@/lib/quantities/client';
import {saveQuantityCapture,openQuantityCapture} from '@/lib/projects/capture-client';
import type {QuantitySnapshot} from '@/lib/projects/snapshots';
import type {ViewCalculation} from '@/lib/quantities-v2/contracts';
import type {QuantityProject,QuantityConfiguration} from '@/lib/quantities/contracts';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
export function QuantityCaptureHistory({project,configuration,data,changed,onCompare}:{project:QuantityProject;configuration:QuantityConfiguration;data:ViewCalculation|null;changed:boolean;onCompare:(data:ViewCalculation)=>void}){
 const [open,setOpen]=useState(false),[runs,setRuns]=useState<QuantitySnapshot[]>([]),[partial,setPartial]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(''),lastAttempt=useRef('');
 async function save(){if(!data||changed)return;setBusy(true);setError('');try{await saveQuantityCapture(project,configuration,data);setSaved(data.calculatedAt);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(data&&!changed&&lastAttempt.current!==data.calculatedAt){lastAttempt.current=data.calculatedAt;void save();}},[data,changed]); // eslint-disable-line react-hooks/exhaustive-deps
 async function list(){setOpen(true);setBusy(true);setError('');try{const r=await quantityResponse<{runs:QuantitySnapshot[];partial:boolean}>(`/api/projects/quantity-history?scope=${encodeURIComponent(JSON.stringify(project))}`);setRuns(r.runs.filter(v=>v.specialtyCode===configuration.specialtyCode));setPartial(r.partial);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function compare(id:string){setBusy(true);setError('');try{const r=await openQuantityCapture(project,id);if(r.data.binding.itemId!==configuration.source?.scope.itemId)throw Error('Esta ejecución corresponde a otro archivo; no se comparará con el modelo activo.');onCompare(r.data);setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className='quantity-capture-status'><span role='status'>{busy?'Guardando / consultando evidencia…':data&&saved===data.calculatedAt?'Lectura guardada con versión, reglas y evidencia':changed?'Guarda los criterios para conservar la siguiente lectura':data?'Lectura de esta sesión':'Esperando lectura'}</span>{data&&saved!==data.calculatedAt&&<button disabled={busy||changed} onClick={()=>void save()}>Guardar lectura</button>}<button onClick={()=>void list()} disabled={busy}>Historial de cubicaciones</button>{error&&<span role='alert'>{error}</span>}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent className='quantity-page quantity-modal quantity-history-modal'><DialogTitle>Cubicaciones guardadas</DialogTitle><DialogDescription>Capturas del motor determinístico del visor. Se verifica el archivo y la versión en Autodesk al guardarlas; no equivalen a una segunda inspección independiente del modelo en el servidor.</DialogDescription>{error&&<p role='alert'>{error}</p>}{partial&&<p>Mostrando las 50 capturas más recientes del proyecto.</p>}{!busy&&!runs.length&&<p>No se encontraron lecturas guardadas para esta especialidad.</p>}{runs.map(r=><article className='configuration-legacy' key={r.id}><div><span><strong>{r.source.fileName} · V{r.source.version.number}</strong><small>{r.source.view?.name} · {new Date(r.calculatedAt).toLocaleString('es-CL')}</small><small>{r.source.version.id===configuration.source?.version.id&&r.source.view?.id===configuration.source?.view?.id?'Coincide con la fuente configurada; publicación por verificar':'Otra versión o vista · resultado histórico'}</small><small>{r.coverage.inspected} elementos · {r.engine} · revisión {r.configurationRevision}</small></span><button disabled={busy||r.source.scope.itemId!==configuration.source?.scope.itemId} onClick={()=>void compare(r.id)}>Cargar para comparar</button></div></article>)}</DialogContent></Dialog></>;
}
