"use client";
import { useState } from 'react';
import type { ModelElement } from '@/lib/quantities-v2/contracts';
import { metricLabels, metricUnits, numberText, type Metric } from '@/lib/quantities-v2/presentation';
const sourceLabels:Record<string,string>={REVIT_PARAMETER:'Parámetro Revit',BIM_GEOMETRY:'Geometría publicada',CALCULATED_GEOMETRY:'Cálculo geométrico',CALCULATED_PARAMETERS:'Cálculo sobre parámetros',NOT_AVAILABLE:'No disponible'};
export function QuantityElementEvidence({records,onLocate,onFloor,onFoundation,busy}:{records:ModelElement[];onLocate:(dbIds:number[])=>void;onFloor:(dbId:number,label:string)=>Promise<void>;onFoundation:(dbId:number)=>Promise<void>;busy:boolean}){
 const [page,setPage]=useState(0),[selected,setSelected]=useState<number|null>(null),[manual,setManual]=useState(''),[error,setError]=useState('');
 const element=records.find(r=>r.dbId===selected),slice=records.slice(page*50,page*50+50);
 return <div className="qv2-evidence"><p className="quantity-help">{records.length.toLocaleString('es-CL')} elementos de la vista leída. Un dato ausente no equivale a cero.</p><div className="qv2-config-table"><table><thead><tr><th>Elemento</th><th>Especialidad / categoría</th><th>Piso resuelto / original</th><th>Hormigón m³</th><th>Moldaje m²</th><th>Acero kg</th></tr></thead><tbody>{slice.map(r=><tr key={r.dbId}><td><button className="quantity-text-button" onClick={()=>{setSelected(r.dbId);setManual('');setError('');}}>{r.elementId??r.externalId??`dbId ${r.dbId}`}</button><small>{r.text.type.value??r.name}</small></td><td>{r.specialty??'Sin especialidad válida'}<br/>{r.category??r.originalCategory??'Categoría no disponible'}</td><td>{r.floor.resolvedBuildingLevel}<br/><small>Revit: {r.floor.originalRevitLevel??'No disponible'}{r.floor.multilevel?' · Multinivel':''}</small></td>{(['concrete','formwork','rebar'] as Metric[]).map(m=><td key={m} title={r.quantities[m].issue??r.quantities[m].formula}>{numberText(r.quantities[m].value)}</td>)}</tr>)}</tbody></table></div><div className="quantity-inline-actions"><button className="quantity-secondary" disabled={!page} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page+1} de {Math.max(1,Math.ceil(records.length/50))}</span><button className="quantity-secondary" disabled={(page+1)*50>=records.length} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div>
 {element&&<section className="qv2-element"><h3>{element.name||`Elemento ${element.dbId}`}</h3><p>{element.source.fileName} · {element.source.viewName} · V{element.source.versionNumber}</p><div className="quantity-inline-actions"><button className="quantity-secondary" disabled={!element.specialty} onClick={()=>onLocate([element.dbId])}>Aislar elemento en el visor</button></div><dl><dt>ElementId / dbId</dt><dd>{element.elementId??'ElementId no disponible'} / {element.dbId}</dd><dt>Identificador externo</dt><dd>{element.externalId??'No disponible'}</dd><dt>Categoría original</dt><dd>{element.originalCategory??'No disponible'}</dd><dt>Familia / tipo</dt><dd>{element.text.family.value??'No disponible'} / {element.text.type.value??'No disponible'}</dd><dt>Material</dt><dd>{element.text.material.value??'No disponible'}</dd></dl>
 {(['concrete','formwork','rebar'] as Metric[]).map(m=>{const q=element.quantities[m];return <details key={m} open><summary>{metricLabels[m]}: {numberText(q.value)} {metricUnits[m]} · {sourceLabels[q.source]}</summary><p>{q.formula??q.issue}</p>{q.issue&&q.formula&&<p className="quantity-warning">{q.issue}</p>}{q.proposedValue!=null&&<div><p>Área potencial para revisar: {numberText(q.proposedValue)} m². Excluida de la suma confirmada.</p><p className="quantity-help">Confirma únicamente si todas las caras verticales requieren moldaje y no hay contactos que descontar.</p><button className="quantity-secondary" disabled={busy} onClick={()=>void onFoundation(element.dbId).catch(e=>setError(e.message))}>Confirmar caras verticales expuestas</button></div>}{q.inputs.map((v,i)=><p key={i}>{v.category} / {v.name}: {v.rawValue} {v.unit}</p>)}{(q.source==='BIM_GEOMETRY'||q.source==='CALCULATED_GEOMETRY')&&<p className="quantity-help">Calculado sobre la malla publicada de Autodesk; su precisión depende de la teselación. No equivale al núcleo geométrico original de Revit.</p>}</details>;})}
 {element.specialty==='Enfierradura'&&<details open><summary>Detalle de barra y tabla de peso</summary><dl><dt>Diámetro</dt><dd>{numberText(element.rebar.diameterMm)} mm</dd><dt>Largo individual / cantidad</dt><dd>{numberText(element.rebar.barLengthM)} m / {numberText(element.rebar.count)}</dd><dt>Largo total</dt><dd>{numberText(element.rebar.totalLengthM)} m</dd><dt>kg/m</dt><dd>{numberText(element.rebar.unitWeightKgM)}</dd><dt>Host / categoría del Host</dt><dd>{element.text.host.value??'No disponible'} / {element.text.hostCategory.value??'No disponible'}</dd><dt>Fuente y versión de coeficiente</dt><dd>{element.rebar.table?`${element.rebar.table.source} · ${element.rebar.table.version}`:'Pendiente'}</dd></dl></details>}
 <details open><summary>Asignación de piso: {element.floor.resolvedBuildingLevel}</summary><p>Nivel Revit: {element.floor.originalRevitLevel??'No disponible'} · Método: {element.floor.floor_assignment_method??'Sin resolver'}</p><p>Confianza registrada: {numberText(element.floor.floor_confidence,2)} / 1 · {element.floor.status}</p><p className="quantity-help">En el método espacial, la confianza expresa la fracción de altura en el piso predominante; no es una probabilidad de IA. La comprobación horizontal utiliza las cajas delimitadoras de las losas.</p>{element.floor.issue&&<p className="quantity-warning">{element.floor.issue}</p>}<label>Corregir piso de este elemento<input value={manual} onChange={e=>setManual(e.target.value)} placeholder="Nombre de piso validado por ti" maxLength={500}/></label><button className="quantity-secondary" disabled={!manual.trim()||busy} onClick={()=>{setError('');void onFloor(element.dbId,manual.trim()).then(()=>setManual('')).catch(e=>setError(e.message));}}>Confirmar asignación manual</button>{error&&<p role="alert" className="quantity-error">{error}</p>}</details>
 <details><summary>Parámetros extraídos y unidades originales</summary>{Object.entries(element.measures).map(([k,v])=><p key={k}><strong>{k}</strong>: {numberText(v.value)} · {sourceLabels[v.source]} {v.issue}<br/>{v.inputs.map(p=>`${p.category} / ${p.name}: ${p.rawValue} ${p.unit}`).join(' · ')}</p>)}{Object.entries(element.text).map(([k,v])=><p key={k}><strong>{k}</strong>: {v.value??'No disponible'}</p>)}</details><details><summary>Geometría y evidencia espacial</summary><pre>{JSON.stringify({geometry:element.geometry,floor:element.floor},null,2)}</pre></details><details><summary>Identificadores de la fuente</summary><pre>{JSON.stringify(element.source,null,2)}</pre></details></section>}
 </div>;
}
