"use client";
import { BarChart3, Box, Layers, Weight, Ruler, SlidersHorizontal, Table2, Download, RefreshCw, History, GitCompareArrows, Settings2 } from "lucide-react";
import { associateSubspecialty } from "@/public/quantity-classification.js";
import { quantityMetrics, visibleQuantityMetrics, type QuantityFiltersValue, type QuantityTableRow, type Metric } from "@/lib/quantities/presentation";
import type { ModelView, QuantitySource } from "@/lib/quantities/contracts";
const amount=(v:number|null|undefined)=>v==null?"No calculado":new Intl.NumberFormat("es-CL",{maximumFractionDigits:3}).format(v);

export function VersionStatus({state,label}:{state:string;label:string}) { return <span className={`quantity-status state-${state.toLowerCase()}`}>{label}</span>; }
export function VersionActions({update,history,disabled}:{update:()=>void;history:()=>void;disabled:boolean}) { return <><button className="quantity-primary" disabled={disabled} onClick={update}><RefreshCw size={15}/>Actualizar versión</button><button className="quantity-secondary" onClick={history}><History size={15}/>Volver a versión anterior</button></>; }
export function ComparisonAction({onClick}:{onClick:()=>void}) { return <button className="quantity-secondary" onClick={onClick}><GitCompareArrows size={15}/>Generar comparación de versiones</button>; }
export function QuantityTopbar({source,views,busy,status,versionLabel,onView,onLoadViews,onUpdate,onHistory,onCompare,onSettings}:{source:QuantitySource|null;views:ModelView[];busy:boolean;status:string;versionLabel:string;onView:(id:string)=>void;onLoadViews:()=>void;onUpdate:()=>void;onHistory:()=>void;onCompare:()=>void;onSettings:()=>void}) {
  return <div className="quantity-context-topbar"><label>Vista<select aria-label="Vista publicada del modelo" value={source?.view?.id??""} disabled={!source||busy} onChange={e=>onView(e.target.value)}><option value="">Seleccionar vista</option>{views.map(v=><option key={v.id} value={v.id}>{v.name} · {v.role.toUpperCase()}</option>)}</select></label><button className="quantity-icon-button" disabled={!source||busy} onClick={onLoadViews} aria-label="Consultar vistas publicadas"><RefreshCw size={14}/></button><div className="quantity-top-version"><small>Versión del modelo</small><strong>{source?`V${source.version.number}`:"Versión no disponible"}</strong></div><VersionStatus state={status} label={versionLabel}/><div className="quantity-top-actions"><VersionActions disabled={!source||busy} update={onUpdate} history={onHistory}/><ComparisonAction onClick={onCompare}/><button className="quantity-icon-button" onClick={onSettings} aria-label="Configurar fuente BIM y plantilla"><Settings2 size={17}/></button></div></div>;
}
export function QuantityFilters({value,onChange,floors,specialties,subspecialties}:{value:QuantityFiltersValue;onChange:(v:QuantityFiltersValue)=>void;floors:string[];specialties:string[];subspecialties:string[]}) {
  return <section className="quantity-panel quantity-filters"><div className="quantity-panel-heading"><SlidersHorizontal size={18}/><h2>Filtros de cubicación</h2></div><div className="quantity-filter-fields"><label>Especialidad<select value={value.specialty} onChange={e=>onChange({...value,specialty:e.target.value})}><option value="">Todas</option>{specialties.map(v=><option key={v}>{v}</option>)}</select></label><label>Subespecialidad<select value={value.subspecialty} onChange={e=>onChange({...value,subspecialty:e.target.value})}><option value="">Todas</option>{subspecialties.map(v=><option key={v}>{v}</option>)}</select></label><label>Piso<select value={value.floor} onChange={e=>onChange({...value,floor:e.target.value})}><option value="">Todos</option>{floors.map(v=><option key={v}>{v}</option>)}</select></label></div></section>;
}
const icons=[Box,Layers,Weight,Ruler];
export function QuantitySummaryCards({totals,previousTotals,blocker,specialty,onRequirements,onProcess,processDisabled=false,calculating=false}:{specialty:string;onRequirements:()=>void;onProcess?:()=>void;processDisabled?:boolean;calculating?:boolean;totals:Record<Metric,number|null>;previousTotals?:Record<Metric,number|null>;blocker:string}) { return <section className="quantity-panel quantity-summary"><div className="quantity-panel-heading"><BarChart3 size={18}/><h2>Resumen ejecutivo</h2>{onProcess?<button className="quantity-primary" disabled={processDisabled} onClick={onProcess}><RefreshCw size={14}/>{calculating?"Procesando…":"Actualizar cubicación"}</button>:<button className="quantity-secondary" title={blocker} onClick={onRequirements}><Settings2 size={14}/>Revisar requisitos de cálculo</button>}</div><div className="quantity-kpis">{visibleQuantityMetrics(specialty).map(m=>{const i=quantityMetrics.indexOf(m), Icon=icons[i];return <article className={`quantity-kpi kpi-${i}`} key={m.key}><Icon size={24} strokeWidth={1.5}/><div><h3>{m.name}</h3><span>{m.unit}</span></div><strong className={totals[m.key]===null?"quantity-no-value":""}>{amount(totals[m.key])}</strong>{previousTotals?.[m.key]!=null&&previousTotals[m.key]!==0&&totals[m.key]!=null&&<small className="quantity-variation">{new Intl.NumberFormat("es-CL",{maximumFractionDigits:1,signDisplay:"always"}).format((totals[m.key]!-previousTotals[m.key]!)/previousTotals[m.key]!*100)} % respecto a la ejecución comparada</small>}</article>;})}</div></section>; }
export function QuantityTable({rows,totals,unavailable,hasRun,onSelect,selectedIds,specialty}:{specialty:string;rows:QuantityTableRow[];totals:Record<Metric,number|null>;unavailable:number;hasRun:boolean;onSelect:(ids:string[])=>void;selectedIds:string[]}) { return <section className="quantity-panel quantity-detail"><div className="quantity-panel-heading"><Table2 size={18}/><h2>Tabla de partidas</h2><details className="quantity-export"><summary className="quantity-secondary"><Download size={14}/>Exportar</summary><div><button disabled>Excel · No disponible</button><button disabled>PDF · No disponible</button><p>Se habilitarán con resultados y formato de exportación verificados.</p></div></details></div><div className="quantity-grid-scroll"><table><thead><tr><th>Subespecialidad</th><th>Nombre de Tipo</th><th>Piso</th>{visibleQuantityMetrics(specialty).map(m=><th key={m.key}>{m.name}<small>{m.unit}</small></th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className={row.elementIds.some(id=>selectedIds.includes(id))?"is-selected":""}><td><button title={`Texto original del modelo: ${row.subspecialty}`} onClick={()=>onSelect(row.elementIds)} disabled={!row.elementIds.length}>{associateSubspecialty(row.subspecialty).group ?? row.subspecialty}</button></td><td>{row.typeName}</td><td>{row.floor}</td>{visibleQuantityMetrics(specialty).map(m=><td key={m.key}>{amount(row.values[m.key])}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={3+visibleQuantityMetrics(specialty).length}><div className="quantity-table-empty"><Table2 size={30}/><strong>{!hasRun?"Cubicación no procesada":unavailable?"Clasificación de partidas no disponible":"Sin resultados para la selección actual"}</strong><p>{!hasRun?"Las cantidades aparecerán al procesar una plantilla con reglas verificadas.":"No se asignan métricas, tipos ni pisos mediante suposiciones."}</p></div></td></tr>}</tbody><tfoot><tr><th colSpan={3}>Totales</th>{visibleQuantityMetrics(specialty).map(m=><td key={m.key}>{amount(totals[m.key])}</td>)}</tr></tfoot></table></div>{unavailable>0&&<p className="quantity-help">{unavailable} partidas sin correspondencia explícita para esta tabla. Totales no disponibles.</p>}</section>; }
