"use client";
import { useMemo, useState } from 'react';
import { Trash2 } from 'lucide-react';
import { mepSpecialties } from '@/public/quantity-v2/mep-catalog.js';
import type { CalculationSettings, ViewCalculation } from '@/lib/quantities-v2/contracts';
type Rule=NonNullable<CalculationSettings['mepSystemRules']>[number];
export function MEPSystemRules({data,rules,onChange,busy}:{data:ViewCalculation|null;rules:Rule[];onChange:(rules:Rule[])=>void;busy:boolean}){
 const [option,setOption]=useState(''),[specialty,setSpecialty]=useState('');
 const options=useMemo(()=>{const values=new Map<string,{field:Rule['field'];value:string}>();for(const e of data?.records??[]){for(const field of ['specialty','systemType','systemClassification'] as const){const text=field==='specialty'?e.specialtyEvidence:e.text[field];if(text?.value){const value={field,value:text.value};values.set(JSON.stringify(value),value);}}}return [...values.entries()];},[data]);
 const fieldLabels={specialty:'Especialidad',systemType:'Tipo de sistema',systemClassification:'Clasificación de sistema'};
 return <section><h3>Asociaciones MEP confirmadas</h3><p className="quantity-help">Pipes no define una especialidad. Se revisan la especialidad y el sistema publicados. Los valores ambiguos quedan pendientes. Puedes asociar un valor publicado a una especialidad; se guardará en este proyecto y se recalculará cada versión.</p><div className="qv2-config-table"><table><thead><tr><th>Parámetro</th><th>Valor publicado</th><th>Especialidad confirmada</th><th/></tr></thead><tbody>{rules.map((r,i)=><tr key={i}><td>{fieldLabels[r.field]}</td><td>{r.value}</td><td>{r.specialty}</td><td><button className="quantity-icon-button" aria-label={`Quitar asociación ${i+1}`} disabled={busy} onClick={()=>onChange(rules.filter((_,index)=>index!==i))}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div><div className="quantity-inline-actions"><label>Valor publicado<select aria-label="Sistema MEP publicado" value={option} onChange={e=>setOption(e.target.value)} disabled={busy}><option value="">Seleccionar parámetro</option>{options.map(([key,v])=><option key={key} value={key}>{fieldLabels[v.field]} · {v.value}</option>)}</select></label><label>Especialidad confirmada<input aria-label="Especialidad MEP confirmada" list="mep-specialties" value={specialty} onChange={e=>setSpecialty(e.target.value)} placeholder="APF, APC, ALC…" disabled={busy}/><datalist id="mep-specialties">{mepSpecialties.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</datalist></label><button className="quantity-secondary" disabled={!option||!specialty.trim()||busy} onClick={()=>{const found=options.find(([key])=>key===option)?.[1];if(found){onChange([...rules.filter(r=>!(r.field===found.field&&r.value===found.value)),{...found,specialty:specialty.trim()}]);setOption('');setSpecialty('');}}}>Agregar asociación</button></div><p className="quantity-help">APF · Agua fría; APC · Agua caliente; ALC · Alcantarillado; GAS; PCI · Incendio; VNT · Ventilación / Climatización; ELE · Electricidad. Puedes definir otro código de especialidad.</p></section>;
}
