// Public regulation: DS MOP 50/2002, BCN consolidated version 2009-02-10.
// Numeric checks require an explicitly confirmed application scope and BIM mapping.
export const ridaaSource={name:'RIDAA · D.S. MOP 50/2002',version:'2009-02-10',checkedAt:'2026-09-28',url:'https://www.bcn.cl/leychile/navegar?idNorma=207101&idVersion=2009-02-10'};
type BaseRule={id:string;systems:string[];name:string;group:'GEOMETRÍA'|'CONECTIVIDAD'|'HIDRÁULICA'|'NORMATIVA';article:string;requirement:string;dependencies:string;check?:{operator:'>='|'<=';value:number;unit:'mm'|'m'|'%'};application:string};
const inside=['SAN-01'],water=['SAN-03','SAN-05'];
export const ridaaRules:BaseRule[]=[
 {id:'RIDAA-1-5',systems:['SAN-02','SAN-04'],name:'Ámbito de las redes exteriores',group:'NORMATIVA',article:'1 y 5; 94 para alcantarillado',requirement:'Las tablas técnicas del RIDAA se circunscriben a instalaciones interiores. Las redes privadas exteriores requieren NCh 691, NCh 1105 y NCh 1104 según corresponda.',dependencies:'Normas chilenas controladas y clasificación de red privada exterior.',application:'No trasladar límites de redes interiores automáticamente a redes exteriores.'},
 {id:'RIDAA-87-CAP',systems:inside,name:'Dimensionamiento y UEH',group:'HIDRÁULICA',article:'87; anexos 6-A y 6-B',requirement:'Dimensionamiento mediante cálculo racional o anexos aplicables.',dependencies:'Conectores, sentido de flujo, UEH de artefactos y tablas controladas.',application:'Tuberías horizontales y verticales de alcantarillado interior.'},
 {id:'RIDAA-87-DOWN',systems:inside,name:'Diámetros aguas abajo',group:'CONECTIVIDAD',article:'87',requirement:'No disminuir diámetros aguas abajo, aunque aumente la pendiente.',dependencies:'Grafo verificado, diámetro y dirección de flujo por tramo.',application:'Trayectorias verificadas de evacuación; no se infiere dirección por proximidad.'},
 {id:'RIDAA-88-MIN',systems:inside,name:'Pendiente mínima ordinaria',group:'GEOMETRÍA',article:'88, inciso 1',requirement:'Límite inferior ordinario de 3 %. El artículo admite hasta 1 % en losas o casos especiales debidamente justificados.',check:{operator:'>=',value:3,unit:'%'},dependencies:'Pendiente de diseño con unidad, identificación de tramo y revisión de excepciones.',application:'Sólo tuberías que conducen materias fecales o grasosas, sin excepción aplicable. No ventilación, bajantes ni unión domiciliaria.'},
 {id:'RIDAA-88-MAX',systems:inside,name:'Pendiente máxima ordinaria',group:'GEOMETRÍA',article:'88, inciso 1',requirement:'Límite superior ordinario de 15 % para el ámbito indicado.',check:{operator:'<=',value:15,unit:'%'},dependencies:'Pendiente de diseño con unidad y confirmación del ámbito.',application:'Sólo tuberías que conducen materias fecales o grasosas en régimen ordinario. No ventilación, bajantes ni unión domiciliaria.'},
 {id:'RIDAA-89',systems:inside,name:'Carga del cierre hidráulico',group:'NORMATIVA',article:'89',requirement:'Cierre hidráulico o sifón con carga mínima de 50 mm, o dispositivo que cumpla esa función.',check:{operator:'>=',value:50,unit:'mm'},dependencies:'Carga publicada del sifón y tipo de dispositivo confirmado.',application:'Bocas de admisión con sifón convencional. Excluir alternativas funcionales que requieren revisión específica.'},
 {id:'RIDAA-90',systems:inside,name:'Accesibilidad para revisión y limpieza',group:'NORMATIVA',article:'90',requirement:'Las tuberías deben poder revisarse y limpiarse.',dependencies:'Accesos y espacios de mantenimiento verificados.',application:'Instalaciones domiciliarias de alcantarillado.'},
 {id:'RIDAA-91',systems:inside,name:'Última cámara y línea de cierro',group:'GEOMETRÍA',article:'91',requirement:'Cámara accesible, normalmente a no más de 1 m de la línea oficial. Excepciones requieren autorización; sobre 20 m al colector se exige cámara adicional bajo condiciones del artículo.',dependencies:'Cámara identificada, línea oficial, colector y autorizaciones.',application:'Cámara domiciliaria; no aplicar a cualquier cámara del modelo.'},
 {id:'RIDAA-92',systems:inside,name:'Cámaras, cambios de dirección y separación',group:'GEOMETRÍA',article:'92',requirement:'Separación máxima: 30 m con diámetro 100 mm; 50 m con diámetro 150 mm o mayor. El artículo regula confluencias, registros alternativos y ángulo suplementario máximo 120° con salvedades.',dependencies:'Red recorrible, cámaras, longitud del recorrido, diámetros y excepciones.',application:'Cámaras interiores y ramales del ámbito del artículo; no extrapolar a diámetros intermedios.'},
 {id:'RIDAA-93',systems:inside,name:'Registros en descargas',group:'NORMATIVA',article:'93',requirement:'En edificios de tres o más pisos, registros de descarga al menos cada dos pisos y donde sean necesarios para accesibilidad y prueba.',dependencies:'Pisos del edificio, descarga conectada y registros identificados.',application:'Edificios de tres o más pisos.'},
 {id:'RIDAA-97-D',systems:inside,name:'Diámetro de ventilación principal',group:'HIDRÁULICA',article:'97 a)',requirement:'Al menos una ventilación principal de diámetro nominal no inferior a 75 mm por empalme; además debe cumplir su ubicación y dimensionamiento.',check:{operator:'>=',value:75,unit:'mm'},dependencies:'Identificación confirmada de ventilación principal y diámetro nominal.',application:'Sólo ventilación principal. Este chequeo parcial no verifica cantidad por empalme, posición ni capacidad.'},
 {id:'RIDAA-97-NET',systems:inside,name:'Ventilación de ramales y descargas',group:'CONECTIVIDAD',article:'97 b) a j), m)',requirement:'Revisar ventilación según recorrido, artefactos, pisos y diámetros; no disminuir el diámetro de ventilación hacia pisos altos.',dependencies:'Grafo, artefactos y trayectorias; anexo 7 y excepciones.',application:'Aplicar cada condición del artículo al ramal correspondiente.'},
 {id:'RIDAA-97-TOP',systems:inside,name:'Terminación de ventilaciones',group:'GEOMETRÍA',article:'97 k), l)',requirement:'Sobresalir 0,60 m sobre techumbre o 2,50 m en terrazas del último piso; condiciones adicionales para patios de luz.',dependencies:'Terminales, cubierta, terraza y fachadas verificadas.',application:'Depende del tipo y contexto de la salida; requiere información arquitectónica.'},
 {id:'RIDAA-52-CU',systems:water,name:'Diámetro mínimo de cobre',group:'HIDRÁULICA',article:'52 a)',requirement:'Mínimo ordinario 13 mm; excepción de 10 mm para tramo a la vista hacia llave o artefacto, de hasta 20 cm.',check:{operator:'>=',value:13,unit:'mm'},dependencies:'Material cobre, diámetro nominal y descarte de excepción.',application:'Tubería de cobre de instalación interior; no tramo excepcional de conexión. El mínimo no sustituye dimensionamiento hidráulico.'},
 {id:'RIDAA-52-PL',systems:water,name:'Diámetro mínimo de plástico',group:'HIDRÁULICA',article:'52 a)',requirement:'Diámetro mínimo 16 mm para material plástico; todos los diámetros deben determinarse por cálculo.',check:{operator:'>=',value:16,unit:'mm'},dependencies:'Material plástico y diámetro nominal confirmados.',application:'Tuberías de plástico de instalación domiciliaria interior. No sustituye dimensionamiento hidráulico.'},
 {id:'RIDAA-52-QMP',systems:water,name:'QI y QMP',group:'HIDRÁULICA',article:'52 b); anexo 3',requirement:'Grifería corriente: QMP = 1,7391 × QI^0,6891, ambos en L/min. Válvulas automáticas y redes mixtas tienen condiciones específicas.',dependencies:'Artefactos conectados, gastos unitarios controlados y tipo de grifería.',application:'No sumar caudales de tramos como si fueran consumos de artefactos.'},
 {id:'RIDAA-52-HYD',systems:water,name:'Velocidad, pérdidas y presión',group:'HIDRÁULICA',article:'52 d), f)',requirement:'Verificar pérdidas y presión en el punto desfavorable. El artículo remite a NCh 2485 para velocidades y presión mínima y contempla condiciones y excepciones.',dependencies:'NCh 2485 controlada, caudales, diámetros interiores, rugosidad, accesorios y condición de suministro.',application:'No fijar un límite universal de velocidad o presión sin revisar ámbito y norma referida.'},
 {id:'RIDAA-52-VAL',systems:water,name:'Llaves de paso por sala',group:'NORMATIVA',article:'52 e)',requirement:'Cada sala de servicio debe poder independizarse mediante una llave de agua fría y otra de agua caliente.',dependencies:'Salas, equipos, válvulas y grafo de conexiones.',application:'Revisión separada de AF y ACS; requiere identificación de salas y alimentación.'},
];
