'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Play,RefreshCw,Settings2,Layers,Box,MapPin,Grid2X2,ListChecks} from 'lucide-react';
import {useProjectContext} from '../project-context';
import {auditResponse} from './audit-context';
import {coordinateFields} from '@/lib/audit/coordinates';
import type {ProjectAuditOverview,ProjectAuditResult} from '@/lib/audit/project';
const sections=[['models','Modelos',Box],['coordinates','Coordenadas',MapPin],['levels','Niveles',Layers],['grids','Ejes y grillas',Grid2X2],['categories','Categorías',ListChecks],['findings','Hallazgos',ListChecks]] as const;
export function AuditProjectOverview(){
 const p=useProjectContext();
 return <ProjectOverview key={[p.owner,p.hubId,p.projectId,p.configuration?.revision].join(':')}/>;
}
function ProjectOverview(){
 const p=useProjectContext(),[data,setData]=useState<ProjectAuditOverview|null>(null),[section,setSection]=useState<string>('models'),[filter,setFilter]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[running,setRunning]=useState(false),[states,setStates]=useState<Record<string,string>>({}),[refresh,setRefresh]=useState(0);
 const abort=useRef<AbortController|null>(null);
 useEffect(()=>{const controller=new AbortController();void auditResponse<ProjectAuditOverview>(p.project,undefined,'&overview=1',controller.signal).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>{controller.abort();abort.current?.abort();};},[p.project,refresh]);
 async function runAll(force=false){if(!data)return;const controller=new AbortController();abort.current=controller;setRunning(true);setError('');setStates({});
  try{for(const row of data.rows){if(controller.signal.aborted)break;if(!row.ready){setStates(s=>({...s,[row.id]:row.reason??'Pendiente'}));continue;}
   setStates(s=>({...s,[row.id]:'Procesando…'}));try{const response=await auditResponse<{result:ProjectAuditResult;reused:boolean}>(p.project,{action:'run-discipline',disciplineId:row.id,revision:data.revision,force},'',controller.signal);if(controller.signal.aborted)break;
    setData(d=>d?{...d,rows:d.rows.map(r=>r.id===row.id?{...r,result:response.result}:r)}:d);setStates(s=>({...s,[row.id]:response.reused?'Resultado reutilizado':response.result.status==='PARTIAL'?'Revisión parcial guardada':'Revisión completa guardada'}));
   }catch(e){if(controller.signal.aborted)break;setStates(s=>({...s,[row.id]:'Error: '+(e as Error).message}));}}
  }finally{setRunning(false);}
 }
 const rows=data?.rows??[],visible=rows.filter(r=>!filter||r.id===filter),ready=rows.filter(r=>r.ready).length,reviewed=rows.filter(r=>r.result).length;
 return <div className="audit-page"><header className="audit-heading"><div><p className="eyebrow">AUDITORÍA DEL PROYECTO</p><h1>Resumen de todas las especialidades</h1><p>{p.appProject?.name??p.projects.find(x=>x.id===p.projectId)?.name}</p></div><Link className="quantity-secondary" href="/configuracion/audit"><Settings2 size={15}/>Configurar especialidades</Link></header>
 <section className="audit-card audit-start"><div><h2>Auditar proyecto</h2><Link href="/auditoria-bim/modelo">Historial y revisión individual →</Link><p>Una ejecución para cada modelo habilitado. Las fuentes, versiones y resultados se conservan por separado.</p><p className="audit-muted">Mantén esta página abierta durante la ejecución. Los modelos ya procesados quedan guardados aunque detengas el resto. Se aplican las reglas y tolerancias del módulo a cada especialidad.</p><small>{ready} especialidades listas · {rows.length-ready} pendientes · {reviewed} con resultados para los criterios actuales</small></div><div className="audit-actions"><button className="quantity-primary" disabled={running||loading||!ready} onClick={()=>void runAll()}><Play size={15}/>{running?'Auditando proyecto…':'Auditar proyecto'}</button><button className="quantity-secondary" disabled={running||loading||!ready} onClick={()=>void runAll(true)}>Reprocesar todas</button>{running&&<button className="quantity-secondary" onClick={()=>abort.current?.abort()}>Detener</button>}<button className="quantity-secondary" disabled={running||loading} onClick={()=>{setLoading(true);setError('');setRefresh(v=>v+1);}}><RefreshCw size={15}/>Actualizar</button></div></section>
 {error&&<p className="audit-alert" role="alert">{error}</p>}{loading&&<p role="status">Consultando resultados guardados…</p>}
 {!!Object.keys(states).length&&<section className="audit-card" aria-live="polite"><h2>Avance por especialidad</h2>{rows.map(row=><p key={row.id}><strong>{row.name}:</strong> {states[row.id]??(running?'En espera':'No procesada en esta operación')}</p>)}</section>}
 {!loading&&!rows.length&&<section className="audit-card"><h2>Configura las especialidades del proyecto</h2><p>Agrega todas las especialidades y sus archivos, versiones y vistas. También puedes recuperar fuentes anteriores del mismo proyecto.</p><Link href="/configuracion/audit">Configurar especialidades →</Link></section>}
 <nav className="audit-actions audit-project-tabs" aria-label="Resumen consolidado">{sections.map(([id,label,Icon])=><button className={section===id?'quantity-primary':'quantity-secondary'} key={id} aria-pressed={section===id} onClick={()=>setSection(id)}><Icon size={16}/>{label}</button>)}</nav>
 <section className="audit-card"><div className="audit-title-row"><h2>{sections.find(([id])=>id===section)?.[1]}</h2><label>Filtrar especialidad<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas las especialidades</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div><p className="audit-muted">Los resultados corresponden a las versiones configuradas; no confirman la última publicación de Autodesk. Una revisión parcial no equivale a cumplimiento. Los datos de distintos modelos no se suman como elementos únicos.</p>
 <div className="audit-table-wrap"><table><thead><tr><th>Especialidad / modelo</th><th>Versión y estado</th><th>{sections.find(([id])=>id===section)?.[1]}</th><th>Detalle</th></tr></thead><tbody>{visible.map(row=>{const r=row.result;return <tr key={row.id}><td><strong>{row.name}</strong><br/>{row.source?.fileName??'Sin archivo'}</td><td>{row.source?'V'+row.source.version.number+' · '+(row.source.view?.name??'Sin vista'):'Pendiente'}<br/>{states[row.id]?.startsWith('Error:')?'Último intento con error · resultado anterior abajo':r?r.status==='PARTIAL'?'Revisión parcial':'Revisión completa':row.reason??'Sin ejecución con los criterios actuales'}{r&&<small><br/>Lectura: {new Date(r.completedAt).toLocaleString('es-CL')}</small>}</td><td>{!r?<span>{row.reason??'Sin resultados disponibles'}</span>:<ResultData section={section} result={r}/>}</td><td>{r?<Link href={'/auditoria-bim/'+({models:'ficha',coordinates:'coordenadas',levels:'niveles',grids:'grillas',categories:'categorias',findings:'hallazgos'}[section]??'ficha')+'?run='+r.id}>Abrir detalle →</Link>:<Link href="/configuracion/audit">Configurar</Link>}</td></tr>;})}</tbody></table></div></section></div>;
}
function ResultData({section,result:r}:{section:string;result:ProjectAuditResult}){
 if(section==='models')return <><p>{r.elementCount??'No disponible'} elementos del alcance · {r.missing} sin propiedades recuperadas</p><small>Motor {r.engineVersion} · Reglas {r.ruleSetVersion}</small></>;
 if(section==='coordinates')return <>{r.coordinates.coordinateData.some(d=>d.status==='AVAILABLE')?r.coordinates.coordinateData.filter(d=>d.status==='AVAILABLE').map(d=><p key={d.field}>{coordinateFields[d.field]}: <code>{JSON.stringify(d.values)}</code></p>):'Coordenadas no disponibles'}<p className="audit-muted">Comparación entre modelos: no evaluada; se muestran las evidencias individuales.</p></>;
 if(section==='levels')return <><p>{r.levels.length} referencias en la vista</p>{r.levels.slice(0,8).map(l=><div key={l.id}>{l.name} · Elevación: {l.elevation==null?'No disponible':String(l.elevation)}</div>)}<p>{r.aecLevels.some(f=>f.levels)?'Niveles AEC (separados de las referencias de la vista):':'Niveles AEC no disponibles'}</p>{r.aecLevels.flatMap(f=>f.levels?.records??[]).slice(0,8).map(l=><div key={l.key}>{l.name??'Sin nombre'} · Elevación AEC: {l.elevation??'No disponible'}</div>)}<small>Ver detalle para consultar unidades, documentos y cobertura completa.</small></>;
 if(section==='grids')return <><p>{r.grids.length} grillas en la vista</p>{r.grids.slice(0,8).map(g=><div key={g.id}>{g.name}</div>)}<p>{r.aecGrids.some(f=>f.available)?'Grillas AEC disponibles: consultar detalle por documento.':'Grillas AEC no disponibles'}</p></>;
 if(section==='categories')return <>{r.categories.map(c=><p key={c.name}>{c.name}: {c.count}</p>)}{!r.categories.length&&'Sin categorías recuperadas'}</>;
 return <><p>{r.metrics.totalRules} controles · {r.metrics.evaluated} evaluados · {r.metrics.pending} con pendientes</p><p>{r.metrics.counts.FAIL} fallos · {r.metrics.counts.WARNING} advertencias · {r.metrics.counts.NOT_EVALUATED} no evaluados</p></>;
}
