'use client';
import Link from 'next/link';
import {coordinateExtraction,coordinateFields} from '@/lib/audit/coordinates';
import {auditHref} from '@/lib/audit/navigation';
import type {AuditRun} from '@/lib/audit/contracts';
import type {QuantitySource} from '@/lib/quantities/contracts';
const fmt=(value:number|null|undefined)=>value==null?'No disponible':value.toLocaleString('es-CL');
export function DatumCounts({run}:{run:AuditRun}){const i=run.inventory;return <><div><dt>Niveles</dt><dd>{i.levels.length} en vista · {i.aec?.files.some(f=>f.levels)?fmt(i.aec.files.reduce((n,f)=>n+(f.levels?.records.length??0),0)):'No disponible'} AEC</dd></div><div><dt>Grillas</dt><dd>{i.grids.length} en vista · {i.aec?.files.some(f=>f.gridsFieldAvailable)?fmt(i.aec.files.reduce((n,f)=>n+f.grids.length,0)):'No disponible'} AEC</dd></div></>;}
export function AuditModelCard({run,source,discipline}:{run?:AuditRun|null;source?:QuantitySource|null;discipline?:string}){const s=run?.source??source;return <section className="audit-card audit-context-card"><div className="audit-title-row"><h2>G01 · Ficha del modelo</h2><Link href={auditHref('ficha')}>Ver ficha →</Link></div><dl className="audit-facts"><div><dt>Modelo</dt><dd>{s?.fileName??'Sin configurar'}</dd></div><div><dt>Publicación / vista</dt><dd>{s?`V${s.version.number} · ${s.view?.name??'Vista pendiente'}`:'No disponible'}</dd></div><div><dt>Especialidad declarada</dt><dd>{run?.discipline??discipline??'No disponible'}</dd></div><div><dt>Fecha de publicación</dt><dd>No disponible</dd></div>{run&&<><div><dt>Elementos de la vista</dt><dd>{fmt(run.scope.elementCount)}</dd></div><DatumCounts run={run}/></>}</dl><details><summary>Procedencia y alcance</summary><p>{run?`Lectura: ${new Date(run.completedAt).toLocaleString('es-CL')}. ${run.scope.population}`:'Configura el modelo y ejecuta la auditoría para consultar su inventario.'}</p>{s&&<><p>Autodesk createTime: {s.version.createdAt?new Date(s.version.createdAt).toLocaleString('es-CL'):'No disponible'}. La API no confirma una fecha distinta de publicación de la vista.</p><p>Fuente: {s.version.endpoint}</p></>}{run&&<p>Los registros de vista y AEC pueden representar la misma referencia; no se suman como elementos únicos.</p>}</details></section>;}
export function AuditCoordinatesCard({run,compact=false}:{run?:AuditRun|null;compact?:boolean}){
 const extraction=run?coordinateExtraction(run.inventory):null,found=extraction?.coordinateData.filter(d=>d.status==='AVAILABLE').length;
 return <section className="audit-card audit-context-card"><div className="audit-title-row"><h2>G02 · Coordenadas</h2>{compact&&<Link href={auditHref('coordenadas')}>Ver datos →</Link>}</div><p>{found?`${found} tipos de datos con evidencia publicada`:'Datos de coordenadas no disponibles en esta lectura'}</p><small>Extracción informativa · La comparación se evalúa por separado.</small>{compact&&!!found&&<dl className="audit-facts">{extraction!.coordinateData.filter(d=>d.status==='AVAILABLE').slice(0,3).map(d=><div key={d.field}><dt>{coordinateFields[d.field]}</dt><dd title={JSON.stringify(d.values[0])}>{JSON.stringify(d.values[0]).slice(0,160)}{JSON.stringify(d.values[0]).length>160?'…':''}</dd></div>)}</dl>}{!compact&&<><div className="audit-table-wrap"><table><thead><tr><th>Dato</th><th>Lectura / valor publicado</th></tr></thead><tbody>{(Object.entries(coordinateFields) as [keyof typeof coordinateFields,string][]).map(([key,label])=>{const data=extraction?.coordinateData.find(d=>d.field===key);return <tr key={key}><td>{label}</td><td>{data?.status==='AVAILABLE'?<>{data.evidenceIndexes.map(i=>{const e=extraction!.coordinateEvidence[i];return <details key={i}><summary>{e.documentId??(e.dbId!==null?`Objeto ${e.dbId}`:'Documento AEC')} · Ver valor y fuente</summary><pre>{JSON.stringify(e.value,null,2)}</pre><p>Unidad: {e.unit??'Conservada en el valor original, si está publicada; no se infiere.'}</p><p>Ruta: {e.path}</p><p>Fuente: {e.source}</p></details>})}</>:data?.status==='NOT_FOUND'?'NO ENCONTRADO en las fuentes consultadas':'NO DISPONIBLE — lectura no realizada o sin fuente recuperable'}</td></tr>;})}</tbody></table></div><details><summary>Comparación entre modelos · No evaluado</summary><p>{extraction?.coordinateComparison.reason??'No hay una lectura disponible para comparar.'} No se deducen coordenadas compartidas ni un origen (0, 0, 0) a partir de la geometría.</p></details>{!run?.inventory.coordinateEvidence&&<p>Abre una nueva ejecución para recuperar coordenadas. Los informes históricos conservan la evidencia con la que se generaron.</p>}</>}</section>;
}
