'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight,Play,Settings2,ScanSearch,ExternalLink,RefreshCw } from 'lucide-react';
import { AutodeskConnection } from '@/components/autodesk-connection';
import { QuantitySourcePicker } from '@/components/quantity-source-picker';
import { auditRules,auditRuleSetVersion,chapterNames,defaultConfiguration,effectiveTolerances,globalTolerances } from '@/lib/audit/catalog';
import { auditHref,auditNavigation,chapterPages } from '@/lib/audit/navigation';
import { auditResults,type AuditConfiguration,type AuditTolerance,type AuditFinding,type VerticalReferenceCatalog } from '@/lib/audit/contracts';
import { useAudit } from './audit-context';
import { AuditFindings } from './audit-results';
import { AuditGrids } from './audit-grids';

const fmt=(value:number)=>value.toLocaleString('es-CL',{maximumFractionDigits:1});
export function AuditBadge({value}:{value:string}){return <span className={`audit-badge audit-${value.replaceAll(' ','-').replace('/','-').toLowerCase()}`}>{value}</span>;}
export function AuditEmpty({title,children}:{title:string;children:React.ReactNode}){return <section className="audit-card audit-empty"><ScanSearch size={30}/><h2>{title}</h2><p>{children}</p></section>;}
export function AuditPage({section}:{section:string}){
 const a=useAudit(),title=auditNavigation.flatMap(g=>g.items).find(([s])=>s===section)?.[1]??'Resumen';
 const source=a.run?.source??a.workspace?.configuration?.source;
 const chapter=Object.entries(chapterPages).find(([,p])=>p===section)?.[0];
 const dataIndex=auditNavigation.find(g=>g.label==='Datos')!.items.findIndex(([s])=>s===section);
 return <div className="audit-page">
  <header className="audit-heading"><div><p className="eyebrow">AUDITORÍA / {title}</p><h1>{title}</h1></div><AutodeskConnection/></header>
  <div className="audit-context-strip"><span>{a.projects.find(p=>p.id===a.projectId)?.name??'Proyecto por configurar'}</span>{source&&<><span>{source.fileName} · V{source.version.number}</span><span>Vista: {source.view?.name??'Por Configurar'}</span></>}<Link href={auditHref('configuracion')}><Settings2 size={14}/>Configurar</Link></div>
  {a.error&&<div role="alert" className="audit-alert">{a.error}<button disabled={a.busy} onClick={()=>void a.reload()}>Reintentar</button></div>}{a.notice&&<p role="status" className="audit-notice">{a.notice}</p>}{a.busy&&<p role="status" className="audit-notice">Consultando fuentes y guardando evidencia…</p>}
  {a.run&&<p className="audit-run-label">Ejecución del {new Date(a.run.completedAt).toLocaleString('es-CL')} · Versión auditada V{a.run.source.version.number}. No verifica automáticamente la última publicación.</p>}
  {section==='configuracion'||section==='referencias'?<AuditConfigurationView referencesOnly={section==='referencias'} key={`${a.hubId}:${a.projectId}:${a.workspace?.revision??0}`}/>:section==='tolerancias'?<AuditTolerances key={`${a.projectId}:${a.workspace?.companyCatalog.version}:${a.workspace?.projectCatalog.version}`}/>:section==='reglas'?<AuditRules/>:section==='hallazgos'?<AuditFindings/>:chapter?<AuditChapter chapter={chapter}/>:section==='comparaciones'?<AuditEmpty title="Comparaciones · Por Configurar">Las ejecuciones se guardan por separado. La comparación entre modelos, disciplinas y versiones se habilitará con reglas específicas; todavía no produce resultados.</AuditEmpty>:dataIndex>=0?<AuditEmpty title={`D${String(dataIndex+1).padStart(2,'0')} · Por Configurar`}>Esta sección está preparada para su catálogo de datos. No se han definido todavía requisitos de parámetros, completitud, unidades o validez para emitir cumplimiento.</AuditEmpty>:<AuditSummary/>}
 </div>;
}
function AuditSummary(){
 const a=useAudit(),c=a.workspace?.configuration,run=a.run,metrics=run?.metrics;
 return <>
  <section className="audit-card audit-start"><div><h2>Auditoría independiente por vista</h2><p>Selecciona un RVT, una versión y una vista. Revisa las reglas y configura los criterios que correspondan.</p><p className="audit-muted">Especialidad: {c?.discipline??'Por Configurar'} · Rule Set: {c?.ruleSetId??'Por Configurar'}</p></div><div className="audit-actions"><Link className="quantity-secondary" href={auditHref('configuracion')}>Configurar auditoría<ArrowRight size={14}/></Link><button className="quantity-primary" disabled={a.busy||!c?.source?.view} onClick={()=>void a.command({action:'run',revision:a.workspace!.revision}).catch(()=>{})}><Play size={14}/>Ejecutar auditoría</button></div></section>
  <section className="audit-card audit-history"><label>Ejecuciones guardadas<select disabled={a.busy||!a.workspace?.runs.length} value={run?.id??''} onChange={e=>void a.openRun(e.target.value)}><option value="">Selecciona una ejecución</option>{a.workspace?.runs.map(r=><option value={r.id} key={r.id}>{new Date(r.createdAt).toLocaleString('es-CL')} · {r.label}</option>)}</select></label><button className="quantity-secondary" disabled={a.busy||!a.projectId} onClick={()=>void a.reload()}><RefreshCw size={14}/>Recargar historial</button>{a.workspace?.nextCursor&&<small>Se muestran las 100 ejecuciones más recientes. Las anteriores se conservan.</small>}</section>
  {metrics&&run?<>
   <div className="audit-kpis"><div className="audit-card"><span>Conformidad evaluada</span><strong>{metrics.conformity===null?'No evaluada':`${fmt(metrics.conformity)} %`}</strong><small>{metrics.evaluated} reglas con resultado evaluativo</small></div><div className="audit-card"><span>Cobertura de ejecución</span><strong>{metrics.coverage===null?'No evaluada':`${fmt(metrics.coverage)} %`}</strong><small>{metrics.executed} de {metrics.totalRules} reglas · {metrics.pending} con pendientes</small></div><div className="audit-card"><span>Elementos del alcance</span><strong>{fmt(run.scope.elementCount??0)}</strong><small>{run.scope.unavailableCount} sin propiedades recuperadas</small></div><div className="audit-card"><span>Elementos con advertencias / fallos</span><strong>{fmt(metrics.affected)}</strong><small>Identificadores distintos de esta vista</small></div></div>
   <div className="audit-result-counts">{auditResults.map(r=><Link key={r} href={`${auditHref('hallazgos')}?estado=${encodeURIComponent(r)}`}><AuditBadge value={r}/><b>{metrics.counts[r]}</b></Link>)}</div>
   <p className="audit-muted">Conformidad = reglas completamente PASS / reglas con PASS, WARNING o FAIL. INFORMATION, N/A y NOT EVALUATED no penalizan. Las reglas con pendientes se indican en la cobertura.</p>
  </>:<AuditEmpty title="Sin auditoría seleccionada">Configura el alcance y ejecuta una auditoría, o abre una ejecución guardada. Los indicadores aparecerán sólo cuando existan resultados verificables.</AuditEmpty>}
  <div className="audit-chapters">{Object.entries(chapterPages).filter(([id])=>!['G01','G02'].includes(id)).map(([id,page])=>{const fs=run?.findings.filter(f=>f.ruleId.startsWith(id));return <Link href={auditHref(page)} key={id} className="audit-card"><small>{id}</small><h3>{chapterNames[id]}</h3><p>{fs?`${fs.filter(f=>f.result==='NOT EVALUATED').length} controles sin evaluar · ${fs.filter(f=>['WARNING','FAIL'].includes(f.result)).length} advertencias / fallos`:'Sin ejecutar'}</p><ArrowRight size={16}/></Link>;})}</div>
 </>;
}
function AuditConfigurationView({referencesOnly=false}:{referencesOnly?:boolean}){
 const a=useAudit(),[draft,setDraft]=useState<AuditConfiguration>(a.workspace?.configuration??structuredClone(defaultConfiguration));
 function change<K extends keyof AuditConfiguration>(key:K,value:AuditConfiguration[K]){setDraft(d=>({...d,[key]:value}));}
 function map(index:number,key:keyof VerticalReferenceCatalog,value:string){setDraft(d=>({...d,verticalReferences:d.verticalReferences.map((m,i)=>i===index?{...m,[key]:value}:m)}));}
 return <>
  {!referencesOnly&&<section className="audit-card"><h2>Proyecto y especialidad</h2><div className="audit-form-grid"><label>Cuenta Autodesk<select value={a.hubId} disabled={a.busy} onChange={e=>a.setHub(e.target.value)}><option value="">Seleccionar cuenta</option>{a.hubs.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label>Proyecto<select value={a.projectId} disabled={a.busy||!a.hubId} onChange={e=>a.setProject(e.target.value)}><option value="">Seleccionar proyecto</option>{a.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Especialidad<select value={draft.discipline} disabled={a.busy} onChange={e=>change('discipline',e.target.value as AuditConfiguration['discipline'])}><option>ESTRUCTURA</option><option>ARQUITECTURA</option><option>MEP</option></select></label></div>{a.nextPage!==null&&<button disabled={a.busy} className="quantity-text-button" onClick={()=>void a.moreProjects()}>Cargar más proyectos</button>}</section>}
  {a.projectId&&a.workspace&&<>
   {!referencesOnly&&<section className="audit-card"><h2>Archivo, versión y vista de auditoría</h2><p className="audit-muted">El alcance inicial es VIEW. Se audita la vista publicada seleccionada; no se amplía al archivo completo.</p><QuantitySourcePicker project={a.project} source={draft.source} onChange={s=>change('source',s)} disabled={a.busy}/>{draft.source?.view?.role==='2d'&&<p className="audit-alert">Selecciona una vista 3D para esta auditoría.</p>}<dl><dt>Rule Set</dt><dd>{draft.ruleSetId} · v{auditRuleSetVersion}</dd><dt>Empresa</dt><dd>{a.hubs.find(h=>h.id===a.hubId)?.name??"Por Configurar"} · Catálogo v{a.workspace.companyCatalog.version}</dd><dt>Catálogo proyecto</dt><dd>v{a.workspace.projectCatalog.version} · {a.workspace.projectCatalog.version?"Configurado":"Por Configurar"}</dd><dt>Estado</dt><dd>{draft.source?.view?"Vista seleccionada; guardar antes de ejecutar":"Por Configurar"}</dd></dl></section>}
   {referencesOnly&&<section className="audit-card"><h2>Referencias verticales por categoría</h2><p>Los nombres deben coincidir exactamente con las propiedades publicadas de tu modelo. Un mapeo sin confirmar no se utiliza.</p><div className="audit-table-wrap"><table><thead><tr><th>Especialidad</th><th>Categoría</th><th>Base / nivel</th><th>Superior</th><th>Clasificación alternativa</th><th>Estado</th><th/></tr></thead><tbody>{draft.verticalReferences.map((m,i)=><tr key={i}><td><select aria-label={`Especialidad de mapeo ${i+1}`} value={m.discipline} onChange={e=>map(i,'discipline',e.target.value)}>{['ESTRUCTURA','ARQUITECTURA','MEP'].map(s=><option key={s}>{s}</option>)}</select></td>{(['category','baseReference','topReference','classificationReference'] as const).map(k=><td key={k}><input aria-label={`${k} ${i+1}`} value={m[k]} onChange={e=>map(i,k,e.target.value)}/></td>)}<td><select aria-label={`Estado de mapeo ${i+1}`} value={m.status} onChange={e=>map(i,'status',e.target.value)}><option>Por Configurar</option><option>Confirmada</option></select></td><td><button aria-label={`Eliminar mapeo ${i+1}`} onClick={()=>change('verticalReferences',draft.verticalReferences.filter((_,n)=>n!==i))}>Quitar</button></td></tr>)}</tbody></table></div><button className="quantity-text-button" onClick={()=>change('verticalReferences',[...draft.verticalReferences,{discipline:draft.discipline,category:'',baseReference:'',topReference:'',classificationReference:'',status:'Por Configurar'}])}>Agregar categoría</button></section>}
   <div className="audit-actions"><button className="quantity-primary" disabled={a.busy||draft.source?.view?.role==='2d'||draft.verticalReferences.some(m=>!m.category.trim()||m.status==='Confirmada'&&!m.baseReference&&!m.classificationReference)} onClick={()=>void a.command({action:'save',revision:a.workspace!.revision,configuration:draft}).catch(()=>{})}>Guardar configuración</button><Link className="quantity-secondary" href={auditHref('tolerancias')}>Revisar tolerancias</Link><Link className="quantity-secondary" href={auditHref('')}>Ir al resumen</Link></div>
  </>}
  {referencesOnly&&!a.projectId&&<AuditEmpty title="Proyecto por configurar">Selecciona un proyecto en <Link href={auditHref("configuracion")}>Proyecto y vista</Link> para configurar las referencias.</AuditEmpty>}
 </>;
}
function AuditTolerances(){
 const a=useAudit(),[origin,setOrigin]=useState<'COMPANY'|'PROJECT'>('PROJECT'),[editing,setEditing]=useState<AuditTolerance|null>(null),[localError,setLocalError]=useState('');
 const company=a.workspace?.companyCatalog,project=a.workspace?.projectCatalog;
 const values=effectiveTolerances(company?.tolerances??[],project?.tolerances??[]);
 async function save(value:AuditTolerance|null,id:string){
  if(!company||!project)return;
  const catalog=origin==='COMPANY'?company:project;const {rules,naming,equivalences,exceptions}=catalog;
  setLocalError('');try{await a.command({action:'catalog',origin,revision:catalog.version,catalog:{rules,naming,equivalences,exceptions,tolerances:[...catalog.tolerances.filter(t=>t.id!==id),...(value?[{...value,origin}]:[])]}});setEditing(null);}catch(e){setLocalError((e as Error).message);}
 }
 return <section className="audit-card"><div className="audit-title-row"><div><h2>Tolerancias técnicas</h2><p>Herencia: Global → Empresa → Proyecto. 0,00 sin confirmación no habilita una comprobación.</p></div><label>Editar en<select value={origin} onChange={e=>{setOrigin(e.target.value as 'COMPANY'|'PROJECT');setEditing(null);}}><option value="PROJECT">Proyecto</option><option value="COMPANY">Empresa / cuenta Autodesk</option></select></label></div>
 {!a.projectId&&<p className="audit-alert">Selecciona un proyecto en Configuración para guardar criterios.</p>}
 <div className="audit-table-wrap"><table><thead><tr><th>Control</th><th>Área</th><th>Valor</th><th>Unidad</th><th>Origen</th><th>Estado</th><th/></tr></thead><tbody>{values.map(t=><tr key={t.id}><td><small>{t.id}</small><br/>{t.control}</td><td>{t.area}</td><td>{t.value.toFixed(2)}</td><td>{t.unit}</td><td>{t.origin}</td><td><AuditBadge value={t.status}/></td><td><button disabled={!a.workspace||a.busy} onClick={()=>setEditing({...((origin==='COMPANY'?company:project)?.tolerances.find(v=>v.id===t.id)??t),origin})}>Editar</button> <button disabled={!a.workspace||a.busy||!(origin==='COMPANY'?company:project)?.tolerances.some(v=>v.id===t.id)} onClick={()=>void save(null,t.id)}>Heredar / restaurar</button></td></tr>)}</tbody></table></div>
 <button className="quantity-secondary" disabled={!a.workspace||a.busy} onClick={()=>setEditing({id:'',area:'',control:'',unit:'mm',value:0,origin,status:'Por Configurar',evidence:''})}>Agregar tolerancia</button>
 {editing&&<form className="audit-editor" onSubmit={e=>{e.preventDefault();if(!editing.id||!editing.control||!editing.area||editing.status==='Confirmada'&&(!editing.evidence.trim()||editing.unit==='Por Configurar')){setLocalError('Completa identificador, control, área, unidad y fuente de la confirmación.');return;}void save(editing,editing.id);}}><h3>{editing.id||'Nueva tolerancia'} · {origin==='COMPANY'?'Empresa':'Proyecto'}</h3><div className="audit-form-grid">{(['id','control','area','unit'] as const).map(k=><label key={k}>{{id:'Identificador',control:'Control',area:'Área',unit:'Unidad'}[k]}<input required value={editing[k]} disabled={k==='id'&&globalTolerances.some(t=>t.id===editing.id)} onChange={e=>setEditing({...editing,[k]:e.target.value})}/></label>)}<label>Valor<input type="number" min="0" step="any" required value={editing.value} onChange={e=>setEditing({...editing,value:e.target.valueAsNumber})}/></label><label>Estado<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as AuditTolerance['status']})}><option>Por Configurar</option><option>Confirmada</option></select></label></div><label>Fuente o criterio validado<textarea value={editing.evidence} onChange={e=>setEditing({...editing,evidence:e.target.value})} placeholder="Documento, decisión explícita o referencia que sustenta este criterio"/></label>{localError&&<p role="alert" className="audit-alert">{localError}</p>}<div className="audit-actions"><button className="quantity-primary" disabled={a.busy||!Number.isFinite(editing.value)}>Guardar criterio</button><button type="button" className="quantity-secondary" onClick={()=>setEditing(null)}>Cancelar</button></div></form>}
 </section>;
}
function AuditRules(){
 const a=useAudit(),[filters,setFilters]=useState<Record<string,string>>({}),[detail,setDetail]=useState<string|null>(null);
 const rows=auditRules.filter(r=>Object.entries(filters).every(([k,v])=>!v||String(r[k as keyof typeof r])===v));
 const selected=auditRules.find(r=>r.ruleId===detail);
 const disabled=a.workspace?.configuration?.disabledRules??[];
 return <section className="audit-card"><h2>Matriz maestra G01–G08 · v{auditRuleSetVersion}</h2><p>Las reglas se ejecutan sobre la vista configurada. Activar una regla no sustituye un método o criterio faltante.</p><div className="audit-filters">{(['chapter','specialty','category','controlType','configurationStatus'] as const).map(k=><label key={k}>{{chapter:'Capítulo',specialty:'Especialidad',category:'Categoría',controlType:'Tipo de regla',configurationStatus:'Estado'}[k]}<select value={filters[k]??''} onChange={e=>setFilters(f=>({...f,[k]:e.target.value}))}><option value="">Todos</option>{[...new Set(auditRules.map(r=>r[k]))].map(v=><option key={v}>{v}</option>)}</select></label>)}</div><div className="audit-table-wrap"><table><thead><tr><th>ID / regla</th><th>Especialidad / categoría</th><th>Tipo</th><th>Tolerancia</th><th>Resultados posibles</th><th>Estado</th><th>Activo</th></tr></thead><tbody>{rows.map(r=><tr key={r.ruleId}><td><button onClick={()=>setDetail(r.ruleId)}>{r.ruleId} · {r.name}</button></td><td>{r.specialty}<br/><small>{r.category}</small></td><td>{r.controlType}</td><td>{r.tolerance??'No aplica'}</td><td>{r.possibleResults.join(' · ')}</td><td>{r.configurationStatus}</td><td><input aria-label={`Activar ${r.ruleId}`} type="checkbox" checked={!disabled.includes(r.ruleId)} disabled={a.busy||!a.workspace?.configuration} onChange={e=>void a.command({action:'save',revision:a.workspace!.revision,configuration:{...a.workspace!.configuration,disabledRules:e.target.checked?disabled.filter(id=>id!==r.ruleId):[...disabled,r.ruleId]}}).catch(()=>{})}/></td></tr>)}</tbody></table></div>{selected&&<aside className="audit-editor"><div className="audit-title-row"><h3>{selected.ruleId} · {selected.name}</h3><button onClick={()=>setDetail(null)}>Cerrar</button></div><dl><dt>Método</dt><dd>{selected.method}</dd><dt>Fuente</dt><dd>{selected.dataSource}</dd><dt>Evidencia requerida</dt><dd>{selected.evidenceRequired}</dd><dt>Buena práctica</dt><dd>{selected.goodPractice}</dd><dt>Catálogo</dt><dd>{selected.catalog}</dd><dt>Versión</dt><dd>{selected.version}</dd></dl></aside>}</section>;
}
function AuditChapter({chapter}:{chapter:string}){
 const a=useAudit(),run=a.run;
 if(!run)return <AuditEmpty title={`${chapter} · ${chapterNames[chapter]}`}>Abre o ejecuta una auditoría desde el Resumen para consultar este capítulo. <Link href={auditHref('')}>Ir al resumen</Link></AuditEmpty>;
 const findings=run.findings.filter(f=>f.ruleId.startsWith(chapter));
 const rows=chapter==='G03'?run.inventory.levels:chapter==='G04'?run.inventory.grids:[];
 return <>
  {chapter==='G01'&&<section className="audit-card"><h2>Ficha de la fuente auditada</h2><dl><dt>Proyecto</dt><dd>{run.source.projectName}</dd><dt>Modelo</dt><dd>{run.source.fileName}</dd><dt>Versión</dt><dd>V{run.source.version.number}</dd><dt>Vista</dt><dd>{run.source.view?.name}</dd><dt>Especialidad declarada</dt><dd>{run.discipline}</dd><dt>Fecha del análisis</dt><dd>{new Date(run.completedAt).toLocaleString('es-CL')}</dd><dt>Alcance</dt><dd>{run.scope.population}</dd><dt>Reglas / catálogos</dt><dd>{run.ruleSetId} · v{run.ruleSetVersion} · Empresa v{run.companyCatalog.version} · Proyecto v{run.projectCatalog.version}</dd></dl>{run.source.version.webUrl&&<a href={run.source.version.webUrl} target="_blank" rel="noopener noreferrer">Abrir versión en Autodesk <ExternalLink size={13}/></a>}</section>}
  {chapter==='G02'&&<p className="audit-notice">Un modelo aislado no demuestra desalineación entre disciplinas. Sólo se muestran datos de coordenadas con evidencia publicada.</p>}
  {chapter==='G04'&&<AuditGrids key={run.id} inventory={run.inventory}/>}
  {chapter==='G03'&&<section className="audit-card"><h2>Inventario publicado en la vista</h2><p>{run.scope.population}</p>{rows.length?<div className="audit-table-wrap"><table><thead><tr><th>Element ID</th><th>UniqueId</th><th>Nombre</th><th>Categoría</th></tr></thead><tbody>{rows.map(e=><tr key={e.dbId}><td>{e.elementId||`Revit ID no disponible · APS ${e.dbId}`} </td><td>{e.uniqueId??'No disponible'}</td><td>{e.name}</td><td>{e.category??'No disponible'}</td></tr>)}</tbody></table></div>:<p className="audit-notice">No se recuperaron objetos Levels identificables en esta vista. Esto no demuestra su ausencia en el RVT.</p>}</section>}
  <section className="audit-card"><h2>Controles del capítulo</h2><div className="audit-table-wrap"><table><thead><tr><th>Regla</th><th>Resultado</th><th>Descripción / evidencia</th></tr></thead><tbody>{findings.map(f=><tr key={f.id}><td><Link href={`${auditHref('hallazgos')}?hallazgo=${f.id}`}>{f.ruleId} · {f.title}</Link></td><td><AuditBadge value={f.result}/></td><td>{f.description}<AuditValue finding={f}/></td></tr>)}</tbody></table></div>{!findings.length&&<p>No hay reglas activas de este capítulo en esta ejecución.</p>}</section>
 </>;
}
function AuditValue({finding}:{finding:AuditFinding}){return finding.observedValue!==null?<details><summary>Dato observado</summary><pre>{typeof finding.observedValue==='string'?finding.observedValue:JSON.stringify(finding.observedValue,null,2)}</pre></details>:null;}
